NEWS.md, descriptors/ModuleDescriptor-template.json, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDao.java, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageImpl.java, mod-source-record-storage-server/src/main/java/org/folio/services/RecordService.java, mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java, mod-source-record-storage-server/src/main/resources/templates/db_scripts/create_records_view.sql, mod-source-record-storage-server/src/main/resources/templates/db_scripts/schema.json, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/RecordApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SnapshotApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/TestMarcRecordsApiTest.java, ramls/source-record-storage.raml
* Renamed endpoints /snapshot -> /snapshots, /record -> /records, /result -> /sourceRecords
* Renamed entities sourceRecord -> rawRecord, result -> sourceRecord
* Updated SourceRecord to contain rawRecord
* Simplified raml file, removed response overriding
* Updated tests to use entities instead of JsonObjects
* Updated NEWS
=> MODSOURCE-28 Renamed endpoints

mod-source-record-storage-server/src/main/java/org/folio/rest/impl/ModTenantAPI.java
UUID for sample data must be the same as names of the files MARC records are contained in.
=> Bug fix MODSOURCE-36 UUID in Sample Data should not be generated

NEWS.md, descriptors/ModuleDescriptor-template.json, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDao.java, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageImpl.java, mod-source-record-storage-server/src/main/java/org/folio/services/RecordService.java, mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/RecordApiTest.java, ramls/source-record-storage.raml
Overview: Libraries sometimes want to suppress records from discovery by their patrons. Much of the discovery work involves harvesting SRS MARC Bib records via OAI-PMH. When a user updates this flag in the FOLIO instance, the corresponding change should be made to the related SRS MARC Bib record, which then in turn updates the flag in the MARCcat MARC Bib record
=> Modinv 144

Dockerfile, descriptors/ModuleDescriptor-template.json
Use new Alpine base docker image with more recent Java 8 (222) with +UseContainerSupport, and JAVA_OPTIONS MaxRAMPercentage to manage container memory.
See notes at [FOLIO-2358](https://issues.folio.org/browse/FOLIO-2358).
=> MODSOURCE-82 FOLIO-2358 manage container memory

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/services/util/AdditionalFieldsUtil.java
1. The 035 field should indicators 1 and 2 of [blank] (currently no JSON for indicators in the screenshot where 035 looks like a fixed field)
2. The contents of the former 001 field should be in subfield a of the 035 field (currently no subfield)
3. If there are existing 035 fields, the newly-created 035 should be a completely new 035 (since 035 is a repeatable field)
4. If the newly-created 035 matches an existing 035 exactly, then do not add that new 035 field.
5. If possible, put the newly-created 035 fields in numeric order within the 0XX fields (but DO NOT resequence the entire MARC record into numeric order)
=> MODDICORE-43 SRS MARC Bib: Fix formatting of 035 field 

mod-source-record-storage-server/pom.xml
folio-liquibase-util v1.0.0 was released, its new development version is 1.1.0-SNAPSHOT, therefore v0.0.1-SNAPSHOT will no longer be available
=> Update folio-liquibase-util dependency to v1.0.0

NEWS.md, mod-source-record-storage-server/src/main/resources/liquibase/tenant/changelog.xml, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-4.0.0/2020-06-13--12-00-drop-error-records.xml, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-4.0.0/2020-06-13--13-00-drop-marc-records.xml, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-4.0.0/2020-06-13--14-00-drop-raw-records.xml, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-4.0.0/2020-06-13--15-00-drop-records.xml, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-4.0.0/2020-06-13--16-00-drop-snapshots.xml, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-4.0.0/2020-06-13--17-00-drop-functions.xml
Set `changeSet` `runAlways="true"` as RMB schema will recreate tables. Removing tables in schema.json causes authentication to database to fail. Seems as if the tenant database role and credentials are not created unless a table is created.
=> MODSOURCE-144: Delete old tables and functions

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/main/java/org/folio/dao/util/ParsedRecordDaoUtil.java, mod-source-record-storage-server/src/main/java/org/folio/dao/util/RecordDaoUtil.java, mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageSourceRecordsImpl.java, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-0.0.2/2020-06-11--13-00-create-records-table.xml, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-0.0.2/2020-06-11--15-00-create-marc-records-table.xml, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-0.0.2/2020-06-12--13-00-migrate-records.xml, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-0.0.2/2020-06-12--15-00-migrate-marc-records.xml, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceRecordApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java, mod-source-record-storage-server/src/test/resources/mock/records/0f0fe962-d502-4a4f-9e74-7732bec94ee8.json, mod-source-record-storage-server/src/test/resources/mock/records/4c0ff739-3f4d-4670-a693-84dd48e31c53.json, mod-source-record-storage-server/src/test/resources/mock/records/7293f287-bb51-41f5-805d-00ff18a1f791.json, mod-source-record-storage-server/src/test/resources/mock/records/8452daf9-c130-4955-99ce-1c397a218900.json, mod-source-record-storage-server/src/test/resources/mock/records/8f462542-387c-4f06-a01b-50829c7c7b13.json, mod-source-record-storage-server/src/test/resources/mock/records/8fb19e31-0920-49d7-9438-b573c292b1a6.json, mod-source-record-storage-server/src/test/resources/mock/records/be1b25ae-4a9d-4077-93e6-7f8e59efd609.json, mod-source-record-storage-server/src/test/resources/mock/records/d3cd3e1e-a18c-4f7c-b053-9aa50343394e.json, mod-source-record-storage-server/src/test/resources/mock/records/e567b8e2-a45b-45f1-a85a-6b6312bdf4d8.json, mod-source-record-storage-server/src/test/resources/mock/records/ec53a386-9616-428b-92a9-e1f07756ea1f.json, ramls/source-record-storage-source-records.raml
https://issues.folio.org/browse/MODSOURCE-155
Requires https://github.com/folio-org/data-import-raml-storage/pull/175
This PR also addresses a performance issue with get source records. The column leader_record_status is used to condition not null in order to perform join with marc records after offset and limit.
=> MODSOURCE-155: Add MARC leader record status to records and ability to filter by

mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-0.0.2/2020-06-12--12-00-migrate-snapshots.xml, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-0.0.2/2020-06-12--13-00-migrate-records.xml, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-0.0.2/2020-06-12--15-00-migrate-marc-records.xml
Migration will now preserve snapshots and records created and updated dates. If not present on previous snapshot or record they will be set to current date and time of migration.
=> Preserve snapshots and records created and updated dates

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/dao/util/MarcUtil.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceStorageBatchApiTest.java
…lue in column \"description\" violates not-null constraint"[BUGFIX] (#250)
* MODSOURCE-200: Post to /source-storage/batch/records returns "null value in column \"description\" violates not-null constraint"[BUGFIX]
1. Additional error-catching added.
2. NEWS updated.
3. Test-case added.
* MODSOURCE-200: Post to /source-storage/batch/records returns "null value in column \"description\" violates not-null constraint"[BUGFIX]
1. Tests added.
* MODSOURCE-200: Post to /source-storage/batch/records returns "null value in column \"description\" violates not-null constraint"[BUGFIX]
1. Tests fixed.
* MODSOURCE-200: Post to /source-storage/batch/records returns "null value in column \"description\" violates not-null constraint"[BUGFIX]
1. Tests fixed.
* MODSOURCE-200: Post to …
=> MODSOURCE-200-BUGFIX

.rancher-pipeline.yml, NEWS.md, descriptors/ModuleDescriptor-template.json, mod-source-record-storage-server/src/main/resources/log4j2.properties, mod-source-record-storage-server/src/main/resources/vertx-default-jul-logging.properties
1. New config file "vertx-default-jul-logging" for overriding vertx-jul added with disabling(except ERROR log-level) CQL2PgJSON.
2. Disabling CQLWrapper to log4j2.properties added.
3. "-Djava.util.logging.config.file=vertx-default-jul-logging.properties" added for ModuleDescriptor.
4. "-Djava.util.logging.config.file=vertx-default-jul-logging.properties" to the .rancher-config-file.
5. NEWS updated.
=> MODSOURCE-174: Disable CQL2PgJSON & CQLWrapper extra logging in mod-source-record-storage.

NEWS.md, mod-source-record-storage-server/pom.xml, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDao.java, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/main/java/org/folio/dao/util/ErrorRecordDaoUtil.java, mod-source-record-storage-server/src/main/java/org/folio/dao/util/ParsedRecordDaoUtil.java, mod-source-record-storage-server/src/main/java/org/folio/dao/util/RawRecordDaoUtil.java, mod-source-record-storage-server/src/main/java/org/folio/dao/util/RecordDaoUtil.java, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-0.0.3/2021-01-16--08-00-create-records-order-index.xml
resolves [MODSOURCE-182](https://issues.folio.org/browse/MODSOURCE-182)
resolves duplicate [MODSOURCE-204](https://issues.folio.org/browse/MODSOURCE-204)
This provides > 2x speedup of the `/source-storage/records?snapshotId=[snapshot id]&orderBy=order&limit=1000` API that is used in the data import UI. Also, has slight performance improvement on `/source-storage/source-records` API.
A downside is that both of these endpoints will require a request type parameter when introducing more parsed record tables. Previously, the n+1 lazy approach could infer the parsed record table from the record and provide a heterogeneous list of records. Additionally, the n+1 lazy approach is faster for smaller pages.
=> MODSOURCE-204: Join query for get records

NEWS.md, mod-source-record-storage-server/pom.xml
This pull request is to resolve the issue with using Liquibase scripts that utilize later versions of PostgreSQL.
[MODSOURCE-238](https://issues.folio.org/browse/MODSOURCE-238)
Switched outdated embedded postgres plugin with docker maven plugin.
Learned that in order to connect from build process to docker container running in Jenkins CI you have to use container IP and default service ports. Also, that postgres connection URL allows for fallback. This was needed to allow for the build to work locally and in Jenkins.
=> MODSOURCE-238: docker-maven-plugin to support build with newer versions of postgres

NEWS.md, README.md, mod-source-record-storage-server/pom.xml, mod-source-record-storage-server/src/main/java/org/folio/dao/PostgresClientFactory.java, mod-source-record-storage-server/src/test/java/org/folio/dao/PostgresClientFactoryTest.java, mod-source-record-storage-server/src/test/java/org/folio/dao/util/MarcUtilTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/AbstractRestVerticleTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/RecordsGenerationTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/AbstractLBServiceTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/AdditionalFieldsUtilTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibliographicMatchEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java, mod-source-record-storage-server/src/test/resources/postgres-conf-test.json
Switch from embedded postgres to testcontainers for tests.
[MODSOURCE-242](https://issues.folio.org/browse/MODSOURCE-242)
Loosen dependency on RMB postgres client and resolve postgres configuration. During tests bring up postgres testcontainer instead of starting embedded postgres.
=> MODSOURCE-242: Testcontainers

mod-source-record-storage-server/src/main/java/org/folio/dao/util/RecordDaoUtil.java
This PR is to address [MODSOURCE-226](https://issues.folio.org/browse/MODSOURCE-226) which on batch save attempted to save parsed record id that did not match record id.
Always set raw, parsed, and error record id to record id if included.
=> MODSOURCE-226: always update raw, parsed, and error record foreign key to record id

descriptors/ModuleDescriptor-template.json, ramls/source-record-storage-handlers.raml, ramls/source-record-storage-records.raml, ramls/source-record-storage-snapshots.raml, ramls/source-record-storage-source-records.raml, ramls/source-record-storage-test-records.raml
* source-storage-event-handlers API version needs to be bumped as /source-storage/handlers/data-import endpoint was removed 
* versions declared in the ModuleDescriptor should match versions in raml
=> Update interface versions

mod-source-record-storage-server/src/main/java/org/folio/services/handlers/MarcBibliographicMatchEventHandler.java
User should be able to use a MARC-MARC match, and then update the associated Instance
Use post-processing mechanism in data-import-processing-core to load needed entities in mod-inventory after the main marc-2-marc match operation
=> MODSOURCE-219 User should be able to use a MARC-MARC match, and then update the associated Instance

NEWS.md, mod-source-record-storage-server/pom.xml, mod-source-record-storage-server/src/main/java/org/folio/rest/impl/ModTenantAPI.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/AbstractRestVerticleTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/AbstractLBServiceTest.java, pom.xml
Avoid calling postTenantSync and update the tests to reflect it.
Remove overriding postTenant(), leave only loadData(). Some tests added.
More info: https://issues.folio.org/browse/MODSOURCE-250
=> MODSOURSE-250: Make tenant API asynchronous.

mod-source-record-storage-server/src/test/java/org/folio/TestMocks.java, mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java
See https://issues.folio.org/browse/MODSOURCE-251 . Only a PR which changes tests a bit.
Problem with existing test was that it assumes all records in there were MARC. Well. They were,.. but one.
=> Fix Unit test: Not equals : MARC != EDIFACT MODSOURCE-251

mod-source-record-storage-server/src/main/java/org/folio/services/handlers/InstancePostProcessingEventHandler.java
Implement writing entities processing information to the log
Requirement: sent event to log when record updated implicitly only for INSTANCE_UPDATED case
After processing DI_INVENTORY_INSTANCE_UPDATED event DI_SRS_MARC_BIB_RECORD_UPDATED should be sent
[MODSOURMAN-384](https://issues.folio.org/browse/MODSOURMAN-384)
=> MODSOURMAN-384: Implement writing entities processing information to the log

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/services/util/AdditionalFieldsUtil.java, mod-source-record-storage-server/src/test/java/org/folio/services/AdditionalFieldsUtilTest.java
When a MARC record is imported and creates an SRS MARC Bib, if the MARC record has an 003 but no 001, then it should NOT create an 035.
Additional condition added.
More info: https://issues.folio.org/browse/MODSOURCE-248
Should be merged with https://github.com/folio-org/mod-source-record-manager/pull/389
=> MODSOURCE-248: Incoming MARC Bib with 003, but no 001 should not create an 035 [BUGFIX].

mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDao.java, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageStreamImpl.java, mod-source-record-storage-server/src/main/java/org/folio/rest/impl/wrapper/SearchRecordIdsWriteStream.java, mod-source-record-storage-server/src/main/java/org/folio/services/RecordService.java, mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/parser/SearchExpressionParser.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/parser/lexeme/Lexicon.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceStorageStreamApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/SearchExpressionParserUnitTest.java
https://issues.folio.org/browse/MODSOURCE-255
Now the backend returns only a list of record UUIDs. In this technical story the response should follow the schema described below, and return instanceUUIDs.
Requirements/Scope:
- Results should contain a JSON response with keys: records (array of associated instance UUIDS), recordCount (integer)
- A search with no results should have an empty records array and count of 0
Created a custom implementation of io.vertx.core.streams.WriteStream to be able to build HTTP response following the schema:
```
{
"records" : array of instance UUIDs,
"totalCount" : integer
}
```
=> MODSOURCE-255 - Return HTTP response according to the schema

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/services/util/parser/lexeme/Lexicon.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/parser/lexeme/operand/BinaryOperandLexeme.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/parser/lexeme/operand/IndicatorBinaryOperand.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/parser/lexeme/operand/LeaderBinaryOperand.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/parser/lexeme/operand/PositionBinaryOperand.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/parser/lexeme/operand/SubFieldBinaryOperand.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/parser/lexeme/operand/ValueBinaryOperand.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceStorageStreamApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/SearchExpressionParserUnitTest.java
https://issues.folio.org/browse/MODSOURCE-257
In this technical story we need to come up with a syntax for search expressions needed to search by position and implement this search feature.
_Search expression example1: 001.02_05 = '3893'_
_Search expression example2: 001.02_01 = '3'_
The first position (02) is the position of the marc field (001) from where the extracting will be starting, 01 - is the very beginning of the string
The second position (05, 01) means a number of characters to be extracted from the marc field (001) 
I created `PositionBinaryOperand` to implement the search by position using the _substring_ function https://w3resource.com/PostgreSQL/substring-function.php
_Describe the research stage. Add links to blog posts, patterns, libraries or addons used to solve this …
=> MODSOURCE-257 Implement the search by position  

mod-source-record-storage-server/src/main/java/org/folio/services/handlers/InstancePostProcessingEventHandler.java
SRS MARC Bib column indicates the MARC record was "Created" for "Update" operation.
Fixing of sending an event after POST_PROCESSING handling.
[MODSOURCE-263](https://issues.folio.org/browse/MODSOURCE-263)
=> MODSOURCE-263: SRS MARC Bib column indicates the MARC record was "Created" for "Update" operation

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java
Bug review: When we overlay a bib record using Data Import, the Instance updates with the new data, but the View Source record retains the old version of the record. When you open the record with quickMARC however, the updated bib record appears for editing. Saving a change in quickMARC then pushes the updated record into View Source.
It seems like the root cause of this issue is about retrieving not-ACTUAL records from DB. So, there was added one more condition: for the "ACTUAL"-state.
More info: https://issues.folio.org/browse/MODSOURCE-267
=> MODSOURCE-267: View Source does not update when Data Import updates bib record [BUGFIX].

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/services/util/parser/lexeme/operand/IndicatorBinaryOperand.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/parser/lexeme/operand/PresenceBinaryOperand.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceStorageStreamApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/SearchExpressionParserUnitTest.java
Implement presence or absence searches for indicators
* Add support of `is 'present/absent'` in `IndicatorBinaryOperand`. The empty indicator represents the `#` symbol in the database.
=> MODSOURCE-269 Support search by indicator presence

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/verticle/consumers/DataImportConsumersVerticle.java
to process "modify record" action that placed at the end of the actions chain. 
Users need to be able to delete unwanted fields from the MARC record after they have been used for entities creation.
For instance, a user can set up 4 actions: create instance, create holdings, create item (using 947 field as item barcode), modify record (delete 947 field from MARC bib). As a result source marc record is created, instance, holdings, item records are created; data from marc field 947 is used as item barcode. Field 947 should be deleted from marc record.
* subscribe dataImportConsumerVerticle to DI_INVENTORY_HOLDING_CREATED, DI_INVENTORY_ITEM_CREATED events to provide further event processing by srs if it's needed
[MODSOURCE-285](https://issues.folio.org/browse/MODDATAIMP-422)
=> MODSOURCE-285 - Order of execution keeps marc updates from occurring

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/InstancePostProcessingEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/ModifyRecordEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/AdditionalFieldsUtil.java, mod-source-record-storage-server/src/test/java/org/folio/services/ModifyRecordEventHandlerTest.java
Fix logic for 001/003/035 handling for overlaying.
- For instance=MARC: was added mechanism for removing 003 field, if it`s needed.
- For instance=Folio: 001/003/035 logic wasn't applied because ExternalHoldersIds wasn't empty(before we have check, and don`t execute it if ExternalHoldersIds is not empty). **This bug caused that the updated instance can't be saved in mod-inventory, because the new instance has an invalid hrid** (ocm12345, for example, not in0000001). So, in this PR was added a condition, that if instance.id==record.externalHolderIds.instanceId AND  instace.hrid!=record.externalHolderIds.instanceHrid(in this case it reveales, ocm1234!=in0000001), then this mechanism will be executed. This specific case (for not equals between marc-record and instance) was in this bug. 
More …
=> MODSOURCE-310: Handling 001/003/035 handling in SRS for MARC bib records broken

mod-source-record-storage-server/src/main/java/org/folio/services/QuickMarcKafkaHandler.java
Fix: quickMARC updates are not reflected on the Inventory instance record
https://issues.folio.org/browse/MODSOURCE-316
mod-inventory expects to have MARC_BIB in event payload.
=> MODSOURCE-316 Change event payload to contain MARC_BIB

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java, mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java
Fix bug when after editing with quickmarc data import marc updates are erroneously discarded.
https://issues.folio.org/browse/MODSOURCE-318
`processingStartedDate` is required to be populated in snapshot table
=> MODSOURCE-318 Set processingStartedDate for snapshot when updating via QM

NEWS.md, mod-source-record-storage-server/src/main/resources/liquibase/tenant/changelog.xml, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-5.0.6-5.1.3-5.2.0/2021-06-30--16-00-update-snapshot-invalid-statuses.xml
Updating of some older records failed, because they were created by some older jobs that did not complete successfully
Add migration script to correct invalid Snapshot statuses
=> MODSOURCE-329 Add migration script to correct invalid Snapshot statuses

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/ModifyRecordEventHandler.java, mod-source-record-storage-server/src/test/java/org/folio/services/ModifyRecordEventHandlerTest.java
to adjust statuses on the summary page after updating an existing Instance and SRS MARC using single record imports for Overlays
* save record updating result as a new version of the existing record
* link updated record to current import job
[MODSOURMAN-451](https://issues.folio.org/browse/MODSOURMAN-451)
=> MODSOURMAN-451- Log details for Inventory single record imports for Overlays

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/InstancePostProcessingEventHandler.java
to adjust statuses on the summary page after updating an existing Instance and creating a new SRS MARC implicitly using single record imports for Overlays
* publish DI_LOG_SRS_MARC_BIB_RECORD_CREATED event to notify data import log that record has been created during post-processing an event that instance was updated 
[MODSOURMAN-508](https://issues.folio.org/browse/MODSOURMAN-508)
=> MODSOURMAN-508 - Log details for Inventory single record imports for Overlays - Part 2

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/services/ParsedRecordChunksKafkaHandler.java, mod-source-record-storage-server/src/test/java/org/folio/verticle/consumers/ParsedRecordChunkConsumersVerticleTest.java
It is necessary to ensure that while data import record save and error appearing in mod-source-record-storage, used eventChain type available in mod-source-record-manager’s JournalParams enum
- Applied eventChain type in mod-source-record-storage available in JournalParams enum which participates in handling of data import record in mod-source-record-manager.
- Covered with test
https://issues.folio.org/browse/MODSOURMAN-515
=> MODSOURMAN-515  Error log for unknown event type

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/dao/util/RecordType.java, mod-source-record-storage-server/src/main/java/org/folio/rest/impl/InitAPIImpl.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/AbstractMarcEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/MarcAuthorityEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/MarcHoldingsEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/verticle/consumers/DataImportConsumersVerticle.java, mod-source-record-storage-server/src/test/java/org/folio/TestMocks.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/RecordApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceRecordApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceStorageStreamApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/util/QueryParamUtilTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/AbstractMarcEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java, mod-source-record-storage-server/src/test/resources/mock/records/3187432f-9434-40a8-8782-35a111a1491e.json, mod-source-record-storage-server/src/test/resources/mock/sourceRecords/3187432f-9434-40a8-8782-35a111a1491e.json
Storing Marc holdings into SRS
- Added enum MARC_HOLDING in the RecordType
- Added DI_SRS_MARC_HOLDING_RECORD_CREATED in the list of events for DataImportConsumersVerticle
- Created MarcHoldingEventHandler
- Registered MarcHoldingEventHandler in the registerEventHandlers into InitAPIImpl
https://issues.folio.org/browse/MODSOURCE-341
=> MODSOURCE-341 Store MARC Holdings record

NEWS.md, descriptors/ModuleDescriptor-template.json, mod-source-record-storage-client/pom.xml, mod-source-record-storage-server/pom.xml, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDao.java, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageBatchImpl.java, mod-source-record-storage-server/src/main/java/org/folio/services/RecordService.java, mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceStorageBatchApiTest.java, pom.xml, ramls/source-record-storage-batch.raml
Search MARC BIB ids in the system and return invalid HRID 
- Create endpoint for searching invalid MARC BIb ids
- Extend or create new raml for endpoint
- Create DTO for returning response into SRM
- Implement DAO and service layer
- Сhange module descriptor
- Update new version
- Write tests
https://issues.folio.org/browse/MODSOURCE-351
=> MODSOURCE-351 Endpoint to verify invalid MARC Bib ids in the system

mod-source-record-storage-server/src/main/java/org/folio/services/RecordService.java, mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceStorageBatchApiTest.java
Due to the fact that the Postgres has restrictions on the number of query parameters, it is necessary to create a filter for the number of МАRC Bib ids
Add checking number of HRID for endpoint: /source-storage/batch/verified-records.    The number of IDs should not exceed 32767.
https://issues.folio.org/browse/MODSOURCE-354
=> MODSOURCE-354 Filtering the number of MARC Bib ids in the SRS

NEWS.md, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-0.0.2/2020-09-09--15-00-fill-instance-hrid.xml
Currently script to fill instance hrid not passes cheksum validation on envs where it was successfully applied before and this error is triggered:
` liquibase/tenant/scripts/v-0.0.2/2020-09-09--15-00-fill-instance-hrid.xml::2020-09-09--15-00-fill-instance-hrid::VolodymyrRohach was: 8:590448842073a494c41e9c242da24966 but is now: 8:fe37e90b4e88dfcb0784f26aed7ed33f`
`12:16:44.332 [vert.x-eventloop-thread-1] ERROR LiquibaseUtil        [6436779eqId] Error while initializing schema fs00001013_mod_source_record_storage for tenant fs00001013
liquibase.exception.ValidationFailedException: Validation Failed:
1 change sets check sum`
Adding  `<validCheckSum>ANY</validCheckSum>`  will disable checksum validation, I tested locally where this script was already applied previously and I changed …
=> [MODSOURCE-368] Fix "fill-instance-hrid" script for envs where it was applied before

mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-0.0.4/2021-05-27--14-00-update-record-types.xml
After updating mod-srs to version 5.1.4, data import failed with the errors:
WARN RecordDaoImpl [376802223eqId] Error occurred on batch execution: ERROR: invalid input value for enum record_type: "MARC_BIB"
Create a new liquibase changeset to fix bug
https://issues.folio.org/browse/MODSOURCE-360
=> MODSOURCE-360 The DB type MARC did not get updated to MARC_BIB

NEWS.md, mod-source-record-storage-server/pom.xml, mod-source-record-storage-server/src/main/java/org/folio/services/caches/MappingParametersSnapshotCache.java, mod-source-record-storage-server/src/test/java/org/folio/services/ModifyRecordEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/handlers/HoldingsPostProcessingEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/handlers/InstancePostProcessingEventHandlerTest.java, ramls/source-record-storage-records.raml
Remove dependency on SRM client. Use simple http call to SRM to retrieve mapping metadata from SRM
Removed SRM dependency from SRS.
[MODSOURCE-382](https://issues.folio.org/browse/MODSOURCE-382)
=> MODSOURCE-382 Remove dependency on SRM client

NEWS.md, descriptors/ModuleDescriptor-template.json, mod-source-record-storage-server/pom.xml, mod-source-record-storage-server/src/main/java/org/folio/services/caches/JobProfileSnapshotCache.java, mod-source-record-storage-server/src/test/java/org/folio/services/caches/JobProfileSnapshotCacheTest.java
Remove dependency on converter-storage client. Use simple http call to converter-storage to retrieve job profile snapshots from converter-storage.
Add converter storage as optional dependency
By deleting dependency from pom and using RestUtils to perform REST requests.
Converter-storage and srm became as optional interfaces.
Docs regarding optional interfaces: https://github.com/folio-org/okapi/blob/master/doc/guide.md#optional-interfaces
Story to introduce optional interfaces in Okapi: https://issues.folio.org/browse/OKAPI-509
=> MODSOURCE-385. Remove dependency on converter-storage client

NEWS.md, mod-source-record-storage-server/src/test/java/org/folio/services/QuickMarcKafkaHandlerTest.java
In the scope of the Optimistic locking feature, mod-source-record-storage needs to pass along 'relatedRecordVersion' through the event chain. This story intended to add this field and update test(s).
updated raml storage to have the latest updates from the master branch
updated test with new property 'relatedRecordVersion'
=> MODSOURCE-387 - Optimistic locking: mod-source-record-storage modifications

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/main/java/org/folio/dao/exceptions/DuplicateEventException.java, mod-source-record-storage-server/src/main/java/org/folio/errorhandlers/ParsedRecordChunksErrorHandler.java, mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java, mod-source-record-storage-server/src/test/java/org/folio/verticle/consumers/ParsedRecordChunkConsumersVerticleTest.java
Prevent sending events from srs during duplicate event
- Finding a duplicate event by throwing a unique constraint violation
- Throws a custom exception and handles in ParsedRecordChunksErrorHandler (only output to logs, do not send DI_ERROR)
https://issues.folio.org/browse/MODSOURCE-402
=> MODSOURCE-402 Properly handle DB failures during events processing

mod-source-record-storage-server/src/main/java/org/folio/dao/util/IdType.java, mod-source-record-storage-server/src/main/java/org/folio/dao/util/RecordDaoUtil.java, mod-source-record-storage-server/src/main/java/org/folio/rest/impl/InitAPIImpl.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/MarcAuthorityEventHandler.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceRecordApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/util/QueryParamUtilTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcEventHandlerTest.java, mod-source-record-storage-server/src/test/resources/mock/sourceRecords/db70de02-9205-4e05-8333-5848163b82b5.json
To extend enum with authorityId for record with type - MARC_AUTHORITY, refactoring handler
- added authorityId in the IdType
- commented handler for authority
- populated authorityId for record with MARC_AUTHORITY type
- added test case
https://issues.folio.org/browse/MODSOURCE-403
=> MODSOURCE-403 Support authority id for MARC Authority

NEWS.md, mod-source-record-storage-server/pom.xml, pom.xml
Upgrade to RAML Module Builder 33.2.x
update verions:
vertx.version -> 4.1.4
raml-module-builder.version -> 3.2.0
folio-di-support -> 1.4.1
https://issues.folio.org/browse/MODSOURCE-419
=> MODSOURCE-419: Upgrade to RAML Module Builder 33.2.x

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/dao/PostgresClientFactory.java, mod-source-record-storage-server/src/test/resources/postgres-conf-test.json
MAXPOOLSIZE was hardcoded with value = 5
The support for 'maxPoolSize' (DB_MAXPOOLSIZE) from RMB was added
https://issues.folio.org/browse/MODSOURCE-420
=> MODSOURCE-420: The support for 'maxPoolSize' (DB_MAXPOOLSIZE) from RMB was added

NEWS.md, mod-source-record-storage-server/pom.xml, pom.xml
to fix  vulnerability that is present in log4j<= 2.14
* upgrade log4j to 2.16.0
[MODSOURCE-424](https://issues.folio.org/browse/MODSOURCE-424)
=> MODSOURCE-424 - Kiwi R3 2021 - Log4j vulnerability verification and correction

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/consumers/QuickMarcKafkaHandler.java
Kafka Cache is used in QuickMarcKafkaHandler in mod-source-record-storage. Just remove Kafka cache (consumer receiving QM_COMPLETED supports deduplication).
=> MODSOURCE-434 SRS. Remove Kafka cache from QuickMarc handlers

NEWS.md, README.md, mod-source-record-storage-server/pom.xml, mod-source-record-storage-server/src/main/java/org/folio/config/ApplicationConfig.java
Delete all kafka cache occurrences with dependencies
https://issues.folio.org/browse/MODDATAIMP-623
=> MODDATAIMP-623. Remove Kafka cache initialization and Maven dependency

mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/main/java/org/folio/dao/exceptions/DuplicateEventException.java, mod-source-record-storage-server/src/main/java/org/folio/errorhandlers/ParsedRecordChunksErrorHandler.java, mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java
Prevent logging of full stack traces for duplicate event to not confuse that something was wrong
**Example of such stack trace:**
10:01:36.749 [vert.x-worker-thread-0] ERROR KafkaConsumerWrapper [138548eqId] Error while processing a record - id: 81 subscriptionPattern: SubscriptionDefinition(eventType=DI_PARSED_RECORDS_CHUNK_SAVED, subscriptionPattern=FOLIO.Default.\w{1,}.DI_PARSED_RECORDS_CHUNK_SAVED) offset: 2 org.folio.dataimport.util.exception.ConflictException: Event with eventId=4013eb1c-83ce-4782-b6d7-bbda4a4323e3 for handlerId=4d39ced7-9b67-4bdc-b232-343dbb5b8cef is already processed. at org.folio.services.EventProcessedServiceImpl.lambda$collectData$0(EventProcessedServiceImpl.java:28) ~[mod-source-record-manager-server-fat.jar:?] at …
=> Improve logging for handling duplicate events to not write in logs full stack trace

mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
It was found some stack traces in logs for duplicate events processing, duplicate events - expected situations and we need to login them with Info level without stack traces
=> Improve logging for duplicate events with removing stack traces and clarifying error messages

NEWS.md, mod-source-record-storage-server/pom.xml, mod-source-record-storage-server/src/main/java/org/folio/dao/PostgresClientFactory.java
currently when a database connection is closed on DB server-side (or process serving particular connection is terminated)
then an error will occur while using such connection for DB querying
* use connection pool providing connection validation before borrowing from the pool (hikari is proposed in the current solution)
[MODSOURCE-438](https://issues.folio.org/browse/MODSOURCE-438)
https://github.com/brettwooldridge/HikariCP
=> MODSOURCE-438 - SQL exceptions when running CREATE import

NEWS.md, mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/SnapshotServiceTest.java, pom.xml
New 2.4.2 version of Vertx recenly released.
https://github.com/vert-x3/wiki/wiki/4.2.4-Release-Notes#vertx
It contains fixes related to the connection pool that can help to resolve Connect timeout issues, that we observe in logs of the recent vagrant boxes when importing large files.
RMB 33.2.5 also contains Vertx version of 4.2.4.
So expected versions set in module pom:
RMB - 33.2.5
Vertx - 4.2.4
https://issues.folio.org/browse/MODSOURCE-461
=> MODSOURCE-461. Upgrade RMB and Vertx versions that contain fixes for the connection pool

mod-source-record-storage-server/pom.xml, mod-source-record-storage-server/src/main/resources/log4j2.properties, pom.xml
Upgrade RMB and Vertx versions that contain fixes for the connection pool
https://issues.folio.org/browse/MODSOURCE-468
=> MODSOURCE-468: Upgrade RMB to 3.2.6 and Vertx to 4.2.5

NEWS.md, descriptors/ModuleDescriptor-template.json
Undefined permission 'source-storage.records.update'
Fix the typo in permissions definition
=> Fix permission definition for updating records

mod-source-record-storage-server/src/main/java/org/folio/config/ApplicationConfig.java
Even though Kafka message payload was significantly decreased, it is still recommended to adjust MAX_REQUEST_SIZE value to allow importing large files. Setting default value to 4000000 bytes would make adjustment of that property unnecessary.
=> Adjust default max_request_size value

mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/MarcAuthorityDeleteEventHandler.java, mod-source-record-storage-server/src/test/java/org/folio/verticle/consumers/DataImportConsumersVerticleTest.java
Add post-processing for MarcAuthorityDeleteEventHandler
With this change, data-import's EventManager will send an event with the current node containing action profile. Currently, it is sending the current node containing mapping profile.
=> MODSOURCE-481 Add post-processing for MarcAuthorityDeleteEventHandler

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
Improve record type validating before trying insert to database and solve problem with records which contains erorrs at the stage preparation record.
This approach give us the oportunity to avoid NPE
- Checked record type to null and throw exception if  it's null
[MODSOURMAN-724](https://issues.folio.org/browse/MODSOURMAN-724)
=> MODSOURMAN-724 SRM does not process and save error records

descriptors/ModuleDescriptor-template.json
Increase the value of max DB pool size in deployment descriptor to make it consistent with constant from java code.
The default value of max DB pool size declared here:
https://github.com/folio-org/mod-source-record-storage/blob/master/mod-source-record-storage-server/src/main/java/org/folio/dao/PostgresClientFactory.java#L53
In this PR we are adjusting DB_MAXPOOLSIZE value in deployment descriptor to the same value
https://issues.folio.org/browse/MODSOURMAN-712
=> MODSOURMAN-712. Timeout when importing MARC files

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageSourceRecordsImpl.java
during single record import mod-copycat requests source record by import job Id to get a result of import. Previously default sorting was introduced [(MODSOURCE-203)](https://github.com/folio-org/mod-source-record-storage/pull/274) to keep a predictable set of records during page-by-page reading using limit and offset parameters. 
Since during single record import only one source record can be associated with import job for performance needs it makes sense not to apply default sorting. 
* do not apply default sorting when only one record should be retrieved and specified offset=0
[MODSOURCE-482](https://issues.folio.org/browse/MODSOURCE-482)
=> MODSOURCE-482 - One-record OCLC (Create) Data Import takes over 9 seconds

NEWS.md, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-0.0.4/2021-05-19--13-00-drop-unused-set-id-function.xml
Remove unused set_id_in_jsonb function in migration.
- Added runAlways="true" attribute to existing change set which must drop function.
[MODSOURCE-349](https://issues.folio.org/browse/MODSOURCE-349)
=> MODSOURCE-349 Function set_id_in_jsonb is present in migrated Juniper/Kiwi environment

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/AbstractUpdateModifyEventHandler.java
When a record was part of a previous multi-record import, and is then updated via single record import, the wrong record number shows in the log for the Inventory single record import
Added forced set of order when it is update action. 
[MODSOURCE-496](https://issues.folio.org/browse/MODSOURCE-496)
There are a lot of test cases that can only be checked manually.
Also need regression testing for this ticket.
=> MODSOURCE-496 Single record imports show the incorrect record number in the summary log 1st column

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/AbstractUpdateModifyEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/AdditionalFieldsUtil.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibUpdateModifyEventHandlerTest.java
When Inventory Single Record Import is used to overlay an existing Instance, the resulting SRS MARC Bib should not have an 003 field. As of Kiwi, this was working properly. Starting in Lotus, for Instances with Source = MARC, the 003 is accidentally being retained.
Added additional validation to split logic for modify and update actions.
[MODSOURMAN-801](https://issues.folio.org/browse/MODSOURMAN-801)
=> MODSOURCE-508 Inventory Single Record Import: Overlays for Source=MARC Instances retain 003 when they shouldn't

NEWS.md, mod-source-record-storage-server/src/main/resources/log4j2.properties
Improve logging. Added FOLIO-approach for retrieving properties for logging.
Retreiving properties from FolioLoggingContext.
- It seems like these properties are available only for REST-requests.
https://issues.folio.org/browse/MODSOURCE-495
=> MODSOURCE-495: Logs show incorrectly formatted request id.

mod-source-record-storage-server/pom.xml
vertx-dependencies maintain jackson versions via jackson-bom.
=> MODSOURCE-518: Unpin jackson version

mod-source-record-storage-server/pom.xml
Fixing Log4Shell: https://nvd.nist.gov/vuln/detail/CVE-2021-44228
=> MODSOURCE-520: Upgrade log4j from 2.13.3 to 2.17.2 fixing CVE-2021-44228

mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/AbstractUpdateModifyEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/AdditionalFieldsUtil.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcAuthorityUpdateModifyEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibUpdateModifyEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcHoldingsUpdateModifyEventHandlerTest.java
Data Import Updates should add 035 field from 001/003, if it's not HRID or already exists
The data from 001 and from 003 fields should not be lost and field 035 should not contain duplicates.
The field 003 should be deleted during import.
For creating MARC BIB records:
- when 035 field isn't present in MARC BIB, this field should be created;
For updating MARC BIB records:
- when 001 field is not equal to hrId then this data should be saved in a new unique 035 field.
[MODSOURCE-509](https://issues.folio.org/browse/MODSOURCE-509)
=> MODSOURCE-509: Improve generation fo 035 field

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/AbstractPostProcessingEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/AbstractUpdateModifyEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/AdditionalFieldsUtil.java, mod-source-record-storage-server/src/test/java/org/folio/services/AdditionalFieldsUtilTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcAuthorityUpdateModifyEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibUpdateModifyEventHandlerTest.java
Data Import Updates should add 035 field from 001/003, if it's not HRID or already exists
The data from 001 and from 003 fields should not be lost and field 035 should not contain duplicates.
The field 003 should be deleted during import.
For creating MARC BIB records:
- when 035 field isn't present in MARC BIB, this field should be created;
For updating MARC BIB records:
- when 001 field is not equal to hrId then this data should be saved in a new unique 035 field.
[MODSOURCE-509](https://issues.folio.org/browse/MODSOURCE-528)
=> MODSOURCE-528: Improve generation fo 035 field

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
If import of "MARC" records was stopped by user, the created records impossible to update via "Data import" app because it leads to error. The error message: "io.vertx.pgclient.PgException: ERROR: duplicate key value violates unique constraint "idx_records_matched_id_gen" (23505)" displaying when user click on the name of imported record.
Extended statuses via CANCELLED.
JIRA: https://issues.folio.org/browse/MODSOURCE-531
=> MODSOURCE-531: Can't update "MARC" record, which was created by stopped import job.

mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/AbstractUpdateModifyEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/AdditionalFieldsUtil.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibUpdateModifyEventHandlerTest.java
When SRS receives 035 field that contains actual hrid value this field should be removed before saving in DB.
Removing the incorrect 035 field.
[MODSOURCE-528](https://issues.folio.org/browse/MODSOURCE-528)
=> MODSOURCE-528: Remove 035 with actual hrId when exists

mod-source-record-storage-server/pom.xml, pom.xml
Upgrade folio-di-support from 1.4.1 to 1.6.0. This upgrades spring-beans fixing https://nvd.nist.gov/vuln/detail/CVE-2022-22965
Upgrade folio-liquibase-util from 1.4.0 to 1.5.0. This upgrades liquibase-core fixing https://nvd.nist.gov/vuln/detail/CVE-2022-0839
Upgrade PostgreSQL JDBC from 42.3.3 to 42.5.0 fixing https://nvd.nist.gov/vuln/detail/CVE-2022-31197
Upgrade Vert.x from 4.3.1 to 4.3.3 fixing disabled SSL: https://github.com/vert-x3/wiki/wiki/4.3.2-Release-Notes#vertx-web
=> MODSOURCE-535: Upgrade folio-di-support, folio-liquibase-util, PostgreSQL, Vert.x

mod-source-record-storage-server/pom.xml, pom.xml
Upgrade scala-library from 2.13.1 to 2.13.9 fixing Remote Code Execution (RCE) vulnerability:
https://nvd.nist.gov/vuln/detail/CVE-2022-36944
Upgrade kafkaclients from 3.1.0 to 3.1.2 fixing Out-of-Memory vulnerability:
https://nvd.nist.gov/vuln/detail/CVE-2022-34917
Upgrade httpclient from 4.0.1 to 4.5.13 fixing Man-in-the-Middle (MitM):
https://nvd.nist.gov/vuln/detail/CVE-2014-3577
Remove unused jaxrs-code-generator dependency. Only these indirect dependencies are needed and added as direct dependencies: httpclient, mockito-core.
=> MODSOURCE-542: scala 2.13.9, kafkaclients 3.1.2, httpclient 4.5.13

mod-source-record-storage-server/src/main/java/org/folio/dao/util/TenantUtil.java, pom.xml
https://issues.folio.org/browse/MODSOURCE-540
[RMB-348](https://issues.folio.org/browse/RMB-348) introduces the ability to direct the read and write calls to the respective database node, the reader or writer (if the database is configured in such a way). The separation of read and write queries brings performance improvements and scalability as the write node is freed up to do more writing while the read node is busy making retrievals.   Most of the read-only code in RMB has already been updated to communicate to the Read node directly. However, there are many other public RMB APIs that are used for both reading and writing by RMB's clients that have not been updated to exclusively talk to the read node.  To take advantage of the read/write split, mod-source-record-storage should replace …
=> [MODSOURCE-540]Upgrade to RMB v35.0.0

mod-source-record-storage-server/src/test/java/org/folio/rest/impl/AbstractRestVerticleTest.java, pom.xml
According to changes in RMB 35.0.0.0 [RMB-937](https://issues.folio.org/browse/RMB-937) add version "1.0.0" when registering the module in AbstractRestVerticleTest
[MODSOURCE-554](https://issues.folio.org/browse/MODSOURCE-554)
=> MODSOURCE-554: Change registration module in tests

mod-source-record-storage-server/pom.xml, mod-source-record-storage-server/src/main/java/org/folio/services/caches/JobProfileSnapshotCache.java
The cache does not return ProfileSnapshot and record-storage calls converter-storage every time. The same class in mod-inventory works as expected.
Fixed in caffeine 3.1.1
[MODSOURCE-556](https://issues.folio.org/browse/MODSOURCE-556)
=> MODSOURCE-556: Fix behaviour of the cache in JobProfileSnapshotCache class

mod-source-record-storage-server/src/main/java/org/folio/rest/impl/InitAPIImpl.java
_MARC-to-MARC Holdings update stacked_
- Create job profile to update MARC Holdings with match profile MARC-MARC matching (available only via API)
- Import some Holdings records
- Try to update these holdings with created job profile
https://issues.folio.org/browse/MODDATAIMP-722
=> MODDATAIMP-722 - MARC-to-MARC Holdings update stacked

README.md, mod-source-record-storage-server/src/main/java/org/folio/consumers/AuthorityLinkChunkKafkaHandler.java, mod-source-record-storage-server/src/main/java/org/folio/consumers/RecordMappingUtils.java, mod-source-record-storage-server/src/main/java/org/folio/dao/util/ParsedRecordDaoUtil.java, mod-source-record-storage-server/src/main/java/org/folio/rest/impl/InitAPIImpl.java, mod-source-record-storage-server/src/main/java/org/folio/verticle/consumers/AuthorityLinkChunkConsumersVerticle.java, mod-source-record-storage-server/src/test/java/org/folio/services/AuthorityLinkChunkKafkaHandlerTest.java, mod-source-record-storage-server/src/test/resources/parsedMarcRecordLinked.json, mod-source-record-storage-server/src/test/resources/parsedMarcRecordLinkedUpdated.json, mod-source-record-storage-server/src/test/resources/parsedMarcRecordUnlinked.json, ramls/source-record-storage-records.raml
When the authority record in mod-inventory-storage is updated - mod-entities-links triggers an update of linked MARC Bib and Instance records. For this purpose, the module has to subscribe to an event generated by mod-entities-links, then update MARC bib records and publish the event to make corresponding changes to related instance records in mod-inventory-storage
- Subscribe to `links.instance-authority`
- Update MARC bib records based on consumed
- Publish events to `srs.marc-bib` topic
[MODSOURCE-550](https://issues.folio.org/browse/MODSOURCE-550)
=> MODSOURCE-550 Link update: Update MARC bibs according to links.instance-authority event

mod-source-record-storage-server/src/main/java/org/folio/consumers/AuthorityLinkChunkKafkaHandler.java, mod-source-record-storage-server/src/test/java/org/folio/services/AuthorityLinkChunkKafkaHandlerTest.java
JobId passed in event is generated by mod-entities-links so there's no actual DI job nor srs Snapshot associated with this id and srs needs to create a snapshot for linked bib updates by itself.
- create snapshot for linked bib updates before event processing
[MODSOURCE-573](https://issues.folio.org/browse/MODSOURCE-573)
=> MODSOURCE-573 Linked bib update failes because of snapshot absence

mod-source-record-storage-server/src/main/resources/log4j2-json.properties, mod-source-record-storage-server/src/main/resources/log4j2.properties
https://issues.folio.org/browse/MODDATAIMP-758HAide SQL requests (org.folio.rest.persist.PostgresClient) from log files for the next modules:
mod-data-import
mod-source-record-storage
mod-data-import-converter-storage
mod-inventory-storage
This class logs SQL queries at the INFO level, which leads to a very large size of log files.
SRS: a lot of messages like this:
2023-01-05 09:28:12.246 WARN AbstractConfig The configuration 'ssl.protocol' was supplied but isn't a known config.
....
2023-01-05 09:28:12.246 WARN AbstractConfig The configuration 'ssl.truststore.type' was supplied but isn't a known config.
SRM: move to TRACE level or decrease defaultRules json
2023-01-05 01:55:50.850 [vert.x-eventloop-thread-1] [572525/proxy;692150/tenant] [diku] [] [mod_source_record_manager] DEBUG …
=> [MODDATAIMP-758]Imrove logging (hide SQL requests)

mod-source-record-storage-server/src/main/java/org/folio/consumers/AuthorityLinkChunkKafkaHandler.java, mod-source-record-storage-server/src/test/resources/parsedMarcRecordLinkedUpdated.json, mod-source-record-storage-server/src/test/resources/parsedMarcRecordUnlinked.json
Updated fields should remain on the same position
- remove/add field directly by index
[MODSOURCE-578](https://issues.folio.org/browse/MODSOURCE-578)
=> MODSOURCE-578 MARC bib field moved to the end of the fields lists after user updates controlling MARC authority record

mod-source-record-storage-server/src/main/java/org/folio/EntityLinksKafkaTopic.java, mod-source-record-storage-server/src/main/java/org/folio/RecordStorageKafkaTopic.java, mod-source-record-storage-server/src/main/java/org/folio/consumers/AuthorityLinkChunkKafkaHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/EventHandlingUtil.java, mod-source-record-storage-server/src/main/java/org/folio/verticle/consumers/AuthorityLinkChunkConsumersVerticle.java, mod-source-record-storage-server/src/test/java/org/folio/services/AbstractLBServiceTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/AuthorityLinkChunkKafkaHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/util/EventHandlingUtilTest.java, ramls/source-record-storage-records.raml
When SRS consumes an event from `links.instance-authority` it tries to update related SRS records. If the update failed then send an event to `links.instance-authority-stats` topic.
https://issues.folio.org/browse/MODSOURCE-567
=> MODSOURCE-567 Link update report: send event if update failed

mod-source-record-storage-server/pom.xml, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/AbstractPostProcessingEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/AuthorityPostProcessingEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/HoldingsPostProcessingEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/InstancePostProcessingEventHandler.java, mod-source-record-storage-server/src/test/java/org/folio/services/handlers/InstancePostProcessingEventHandlerTest.java
To avoid sending DI_COMPLETED event from di-core lib if there is an "DI_ORDER_CREATED_READY_FOR_POST_PROCESSING"-event in the payload.
Added a new abstract method, and implemented only for the Instance-entity (because the logic inside InstancePostProcessingEventHandler is only for sending events for the logs).
(https://issues.folio.org/browse/MODSOURCE-577)
=> MODSOURCE-577: Prevent Instance PostProcessing Handler from sending DI_COMPLETED.

mod-source-record-storage-server/src/main/java/org/folio/consumers/AuthorityLinkChunkKafkaHandler.java, mod-source-record-storage-server/src/test/java/org/folio/services/AuthorityLinkChunkKafkaHandlerTest.java
Cleanup kafka headers for marc.bib event to have only x-okapi-* headers
=> MODSOURCE-587 Cleanup kafka headers for marc.bib event

mod-source-record-storage-server/src/main/java/org/folio/services/handlers/InstancePostProcessingEventHandler.java, mod-source-record-storage-server/src/test/java/org/folio/services/handlers/InstancePostProcessingEventHandlerTest.java
Update postprocessing method to handle DI orders with instances creation
1. eventType of the message should be set to DI_ORDER_CREATED_READY_FOR_POST_PROCESSING
2. key POST_PROCESSING_RESULT_EVENT should be deleted
3. key POST_PROCESSING_INDICATOR = true should be added to the context 
[MODSOURCE-598](https://issues.folio.org/browse/MODSOURCE-598)
=> MODSOURCE-598: Update postprocessing method to handle DI orders with instances creation

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/consumers/ParsedRecordChunksKafkaHandler.java, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDao.java, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/main/java/org/folio/dao/util/RecordDaoUtil.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/match/AbstractMarcMatchEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/match/MarcBibliographicMatchEventHandler.java, mod-source-record-storage-server/src/test/java/org/folio/dao/PostgresClientFactoryTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibliographicMatchEventHandlerTest.java
there is a case of creating marc-bib records without instance UUID, but with fields which represent other instance identifiers (035$a field). This in turn causes multiple records matching during matching by arbitrary MARC field (e.g. 035$a field) and taking into consideration incorrect marc-bib records (which aren't associated with instances).
* do not consider marc-bib records which have no external id value during records lookup by arbitrary MARC field. Expand RecordsDao#getMatchedRecords() with parameter that indicates whether necessary to avoid records with externalId as null during records lookup.
* add test
[MODSOURCE-585](https://issues.folio.org/browse/MODSOURCE-585)
=> MODSOURCE-585 - Data import matching takes incorrect SRS records into consideration

README.md, mod-source-record-storage-server/src/main/java/org/folio/client/InstanceLinkClient.java, mod-source-record-storage-server/src/main/java/org/folio/services/caches/LinkingRulesCache.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/MarcBibUpdateModifyEventHandler.java, mod-source-record-storage-server/src/test/java/org/folio/client/AbstractClientTest.java, mod-source-record-storage-server/src/test/java/org/folio/client/LinksClientTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibUpdateModifyEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/caches/LinkingRulesCacheTest.java
Update links interactions according to 'instance-authority-links' interface change to 2.0
Add api `/linking-rules/instance-authority` to `InstanceLinkClient`
Add created api call into `MarcBibUpdateModifyEventHandler` (it would be good to cache rules for a few hours, with configurable time, because they are not meant to be changed between releases)
Pass linking rules to `MarcBibRecordModifier`
[MODSOURCE-609](https://issues.folio.org/browse/MODSOURCE-609)
=> MODSOURCE-609: MarcBibUpdateModifyEventHandler and InstanceLinkClient improved

mod-source-record-storage-server/src/main/java/org/folio/dao/util/RecordDaoUtil.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceRecordApiTest.java
The request with GetRecord verb returns inconsistent results when SRS record that was marked was deleted is marked as corrected or new (LDR 05 changes from "d" to "c" or "n")
* Fixed filtering by deleted condition
* Updated unit tests
=> MODSOURCE-637 - OAI-PMH Inconsistent behavior of GetRecord method for "undeleted" record

.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, Jenkinsfile, README.md, ramls/source-record-storage-records.raml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
=> FOLIO-3678 MODSOURCE-634 Use GitHub Workflows api-lint and api-schema-lint and api-doc

mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java, mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java, ramls/source-record-storage-batch.raml
- Add request sample for fetch parsed records in batch endpoint
- Make `data` not requiered
https://issues.folio.org/browse/MODSOURCE-628
=> MODSOURCE-628 Add request sample for fetch parsed records in batch endpoint

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/main/resources/liquibase/tenant/changelog.xml, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-5.7.0/2023-05-22--16-00-create-records-state-index.xml, mod-source-record-storage-server/src/test/java/org/folio/verticle/MarcIndexersVersionDeletionVerticleTest.java
to clean up "marc_indexers" rows associated with "OLD" source records since they are not accounted during search in the "marc_indexers" table.
* modify the existing query for "marc_indexers" table cleanup with condition by "OLD" records state. Add index on the "records_lb"."state" field
* add migration script to clean up rows from "marc_indexers" associated with "OLD" records in "marc_records_lb".
* add test
[MODSOURCE-635](https://issues.folio.org/browse/MODSOURCE-635)
=> MODSOURCE-635 - Delete marc_indexers records associated with old source records

mod-source-record-storage-server/src/main/java/org/folio/verticle/consumers/DataImportConsumersVerticle.java
Allow srs marc to process on instance, holdings, item match event
Added DI_INVENTORY_INSTANCE_MATCHED, DI_INVENTORY_HOLDING_MATCHED, and DI_INVENTORY_ITEM_MATCHED events to the list of srs marc process events
Jira: https://issues.folio.org/browse/MODSOURCE-643
=> [MODSOURCE-643] Allow srs marc processing on instance, holdings, item match event

mod-source-record-storage-server/pom.xml, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/test/java/org/folio/verticle/consumers/ParsedRecordChunkConsumersVerticleTest.java
There is an issue with lingering transactions when exceptions occur within lambda on some code paths. This is caused by a bug captured by the offending library used in SRS, https://github.com/jklingsporn/vertx-jooq/issues/197. 
A symptom of this issue is that database connections are in a "idle in transaction" state for some time after an exception has occurred. Transactions are open but no SQL statements are sent through. The database is left waiting for any interaction before the connection is closed. Top suspect is that the connection is closed when the query executor, which holds a reference to the transaction object, is garbage collected. This also means that for the duration of the connection being held hostage other processes within SRS can't use the connection. In a Data Import …
=>  MODSOURCE-641: Close Transactions After Exceptions Are Thrown

NEWS.md, descriptors/ModuleDescriptor-template.json, mod-source-record-storage-server/src/main/java/org/folio/dao/AsyncMigrationJobDao.java, mod-source-record-storage-server/src/main/java/org/folio/dao/AsyncMigrationJobDaoImpl.java, mod-source-record-storage-server/src/main/java/org/folio/dao/MigrationJobDao.java, mod-source-record-storage-server/src/main/java/org/folio/dao/MigrationJobDaoImpl.java, mod-source-record-storage-server/src/main/java/org/folio/dao/PostgresClientFactory.java, mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageMigrationsJobsImpl.java, mod-source-record-storage-server/src/main/java/org/folio/services/migrations/AsyncMigrationJobRunner.java, mod-source-record-storage-server/src/main/java/org/folio/services/migrations/AsyncMigrationJobService.java, mod-source-record-storage-server/src/main/java/org/folio/services/migrations/AsyncMigrationJobServiceImpl.java, mod-source-record-storage-server/src/main/java/org/folio/services/migrations/AsyncMigrationTaskRunner.java, mod-source-record-storage-server/src/main/java/org/folio/services/migrations/MarcIndexersVersionMigrationTaskRunner.java, mod-source-record-storage-server/src/main/resources/async_migration/delete-old-records-marc-indexers.sql, mod-source-record-storage-server/src/main/resources/async_migration/set-marc-indexers-version.sql, mod-source-record-storage-server/src/main/resources/liquibase/tenant/changelog.xml, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-5.7.0/2023-04-13--16-00-update-fill-in-trigger.xml, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-5.7.0/2023-05-22--16-00-create-records-state-index.xml, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-5.7.0/2023-05-31--16-00-create-async-migration-jobs-table.xml, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/MigrationsJobsApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/migrations/AsyncMigrationJobServiceImplTest.java, ramls/source-record-storage-migrations-jobs.raml
Migration script to populate marc_records_tracking table and version for marc_indexers table should be run asynchronously (not at the module deployment time) through REST API call. 
It's necessary to provide API for the management of asynchronous migrations to run migration scripts, which take a long time to complete, manually and separately from the module deployment time.
* implement asynchronous endpoint `POST /source-storage/migrations/jobs` to initiate asynchronous migration job and appropriate scripts run.
The endpoint allows only one migration job to be in progress. If during the endpoint call another migration job is still being IN_PROGRESS, then the endpoint will respond 409 Conflict in response.
* implement endpoint `GET /source-storage/migrations/jobs/{jobId}` to check the …
=> MODSOURCE-636 - Implement async migration service

mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
The timeout exception appears after trying to catch edited record
- Fetch only ACTUAL records
- Add OLD state for `recordState` enum
https://issues.folio.org/browse/MODSOURCE-647
=> MODSOURCE-647 Bulk endpoint to fetch parsed records. Timeout exception

mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDao.java, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/main/java/org/folio/dao/util/ParsedRecordDaoUtil.java, mod-source-record-storage-server/src/main/java/org/folio/services/RecordService.java, mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/AbstractDeleteEventHandler.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcAuthorityDeleteEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java
Update Leader position when authority record is deleted
_Update Leader position when authority record is deleted_
_When user deletes an authority record update Parsed Record Leader position 05 to value of 'd'_
[_MODSOURCE-639_](https//issues.folio.org/browse/MODSOURCE-639)
=> MODSOURCE-639: Update Leader position when authority record is deleted

Dockerfile, Jenkinsfile, NEWS.md, mod-source-record-storage-server/pom.xml, pom.xml
_Upgrade mod-source-record-storage to Java 17._
_Incorporates **updating folio-liquibase-util** and **folio-kafka-wrapper** version already migrated to Java 17_.
=> MODSOURCE-648: Upgrade mod-source-record-storage to Java 17

mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibliographicMatchEventHandlerTest.java
Add support for wildcards in ind. fields in marc-to-marc matching
Updated sql script that retrieves existing marc record to use "ind LIKE '%'" for indicator with wildcard
Jira: https://issues.folio.org/browse/MODSOURCE-675
=> [MODSOURCE-675] Add support for wildcards in ind. fields in marc-to-marc matching

mod-source-record-storage-server/pom.xml, mod-source-record-storage-server/src/main/java/org/folio/dao/PostgresClientFactory.java, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/AbstractUpdateModifyEventHandler.java, mod-source-record-storage-server/src/test/java/org/folio/dao/RecordDaoImplTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/AbstractRestVerticleTest.java
Allow DI marc-to-marc matching and records search to work correctly until migration scripts which are required by MODSOURCE-601 are completed, in order to avoid downtime during the those scripts execution.
* add alternative/fallback query that performs a search without indexers version usage to DAO method that provides marc-to-marc matching and to the method aimed for retrieving marc identifiers by search query.
This alternative query should be executed when the search results of the current queries are empty and newly introduced parameter `srs.record.matching.fallback-query.enable` = true.
* fix PgException handling in AbstractUpdateModifyEventHandler to prevent import job from being stuck if PgException is not related to matchedId-generation uniqueness constraint violation.
* add tests …
=> MODSOURCE-671 - Allow DI to function correctly if marc_indexers version value is not set

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/main/java/org/folio/dao/util/AdvisoryLockUtil.java, mod-source-record-storage-server/src/test/java/org/folio/dao/RecordDaoImplTest.java
to prevent module instances from blocking each other while attempting to delete marc indexers on the same tenant
* apply advisory lock for deletion marc indexers on certain tenant to prevent this deletion from being executed by multiple module instances for the same tenant at the same time
[MODSOURCE-674](https://issues.folio.org/browse/MODSOURCE-674)
=> MODSOURCE-674 - Ensure only one background job can be triggered to clean up outdated marc indexers

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/main/java/org/folio/dao/util/IdType.java, mod-source-record-storage-server/src/main/java/org/folio/dao/util/RecordDaoUtil.java, mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/AbstractPostProcessingEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/AuthorityPostProcessingEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/HoldingsPostProcessingEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/InstancePostProcessingEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/AbstractUpdateModifyEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/AdditionalFieldsUtil.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/AbstractRestVerticleTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/RecordsGenerationTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceRecordApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceStorageBatchApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceStorageStreamApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/AuthorityLinkChunkKafkaHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcAuthorityUpdateModifyEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibUpdateModifyEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcHoldingsUpdateModifyEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/QuickMarcKafkaHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/handlers/AuthorityPostProcessingEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/handlers/HoldingsPostProcessingEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/handlers/InstancePostProcessingEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/verticle/consumers/DataImportConsumersVerticleTest.java
Duplicate records in incoming file causes problems after overlay process with no error reported
Changed a way of assigning matched id, now it generated during save record process, matched id is retrieved from 999$s field, in case if the parsed record does not contain this field, assigning id of exiting source record with a same external id
=> [MODSOURCE-530] Send DuplicateException if incoming file contains duplicate records

mod-source-record-storage-server/src/main/resources/liquibase/tenant/changelog.xml, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-5.7.0/2023-08-29--16-00-define-version-column-default-value.xml
to replace leverage of migration script for marc_indexers version update by default value column option for marc_indexers "version" column since the script execution takes a lot of time
* add migration script to recreate `marc_indexers.version` column specifying default value as 0
[MODSOURCE-684](https://issues.folio.org/browse/MODSOURCE-684)
=> MODSOURCE-692 - Test adding default value for version column in marc_indexers

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/consumers/ParsedRecordChunksKafkaHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/EventHandlingUtil.java
Upgrade folio-kafka-wrapper to 3.0.0 version
Upgrade the version of folio-kafka-wrapper to 3.0.0 (first, update to latest SNAPSHOT version for testing, then to v3.0.0 after release). Check out the readme at https://github.com/folio-org/folio-kafka-wrapper/blob/master/README.md for usage.
Acceptance Criteria
- kafka records are built using KafkaProducerRecordBuilder
- topic names are generated using KafkaTopicNameHelper
=> MODSOURCE-667 Upgrade folio-kafka-wrapper to 3.0.0 version

mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/AbstractUpdateModifyEventHandler.java, mod-source-record-storage-server/src/test/java/org/folio/services/AbstractLBServiceTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcAuthorityUpdateModifyEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibUpdateModifyEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcHoldingsUpdateModifyEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/handlers/AuthorityPostProcessingEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/handlers/HoldingsPostProcessingEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/handlers/InstancePostProcessingEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/verticle/consumers/DataImportConsumersVerticleTest.java
[MODSOURCE-642](https://issues.folio.org/browse/MODSOURCE-642)  Update 005 field(transaction date) on updating MARC bibliographic/MARC authority/MARC holdings 
Generation of transaction date and setting it to 005 field logic already exists for creating records. Reuse it for updates: add setting 005 field to AbstractUpdateModifyEventHandler.java which contains common logic for update of all record types.
=> MODSOURCE-642 update 005 field(transaction date) on updating MARC record

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibliographicMatchEventHandlerTest.java
Import is completed with errors when control field that differs from 001 is used for marc-to-marc matching
Import marc-bib record using job profile containing marc-to-marc matching and action profile for marc-bib update if a record matches. Marc-to-marc match profile should use a control field that differs from 001 as a match point (e.g. 008).
During investigation  in debug the following exception was found:
"io.vertx.pgclient.PgException: ERROR: syntax error at or near "393893" (42601)"
Due to redundant wrapping of value from incoming field by single quotation marks.
[MODSOURCE-677](https://issues.folio.org/browse/MODSOURCE-677)
=> MODSOURCE-677: Import is completed with errors when control field that differs from 001 is used for marc-to-marc matching

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
MARC authority record is not created when use Job profile with match profile by absent subfield/field. 
[MODSOURCE-709](https://issues.folio.org/browse/MODSOURCE-709)
Fixed condition statement to remove empty value from sql script when matching records
=> MODSOURCE-709 MARC authority record is not created when use Job profile with match profile by absent subfield/field

descriptors/ModuleDescriptor-template.json, mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageRecordsImpl.java, mod-source-record-storage-server/src/main/java/org/folio/services/RecordService.java, mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/RecordApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java, ramls/source-record-storage-records.raml
Add PUT endpoint to update SRS record
Added endpoint with URL `/source-storage/records/{id}/generation` Basically new endpoint execute 'saveRecord' method but only for record with a matched id that already exists at DB, so we are creating a new ACTUAL record with incremented generation
https://issues.folio.org/browse/MODSOURCE-731
=> [MODSOURCE-731] Add PUT endpoint to update SRS record

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/verticle/consumers/DataImportConsumersVerticle.java
MARC modifications not processed when placed after Holdings Update action in a job profile.
ADDED holding update subscription. Also it is checked behavior with item case.
=> MODSOURCE-717: MARC modifications not processed when placed after Holdings Update action in a job profile

NEWS.md, mod-source-record-storage-server/pom.xml, mod-source-record-storage-server/src/main/java/org/folio/consumers/DataImportKafkaHandler.java, mod-source-record-storage-server/src/main/java/org/folio/consumers/ParsedRecordChunksKafkaHandler.java, mod-source-record-storage-server/src/main/java/org/folio/errorhandlers/ParsedRecordChunksErrorHandler.java, mod-source-record-storage-server/src/main/java/org/folio/verticle/consumers/AbstractConsumerVerticle.java, mod-source-record-storage-server/src/main/java/org/folio/verticle/consumers/AuthorityDomainConsumersVerticle.java, mod-source-record-storage-server/src/main/java/org/folio/verticle/consumers/AuthorityLinkChunkConsumersVerticle.java, mod-source-record-storage-server/src/main/java/org/folio/verticle/consumers/DataImportConsumersVerticle.java, mod-source-record-storage-server/src/main/java/org/folio/verticle/consumers/ParsedRecordChunkConsumersVerticle.java, mod-source-record-storage-server/src/main/java/org/folio/verticle/consumers/QuickMarcConsumersVerticle.java, mod-source-record-storage-server/src/main/resources/vertx-default-jul-logging.properties
Reduce memory allocations of strings to reduce memory requirements of SRS and improve performance at the limit
Prior to this change, byte arrays obtained from the Kafka clients are converted to Strings before being passed to a consumer handler. The String is then converted to a POJO for further logic. Due to requirements of data import, kafka payloads can be large. For example, if payload for a parsed MARC record is 1MB(this is a common occurrence), its string representation will be 1MB + other bytes.
After this change, byte arrays are coverted directly to POJO so intermediate Strings are not created. Internally, Jackson streams the byte array rather than create a String representation. This means that memory used is not directly proportional to the size of the kafka payloads encountered. …
=> MODSOURCE-733 Reduce memory allocations of Strings

NEWS.md, README.md, mod-source-record-storage-server/src/main/java/org/folio/rest/impl/ModTenantAPI.java, mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageRecordsImpl.java, mod-source-record-storage-server/src/main/java/org/folio/services/SRSKafkaTopicService.java, mod-source-record-storage-server/src/main/resources/kafka.properties, mod-source-record-storage-server/src/test/java/org/folio/services/kafka/KafkaAdminClientServiceTest.java
Create Kafka topics instead of relying on auto create in mod-srs [MODSOURCE-739](https://issues.folio.org/browse/MODSOURCE-739)
* create kafka topics during tenant init
* add tests
=> MODSOURCE-739 Create Kafka topics instead of relying on auto create in mod-srs

mod-source-record-storage-server/src/main/java/org/folio/rest/impl/ModTenantAPI.java
curb blocking of the eventloop when tenant schema initialization occurs
run tenant schema initialization on a worker thread away from the eventloop.
=> MODSOURCE-758 execute schema init on non-eventloop thread

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/AbstractPostProcessingEventHandler.java, mod-source-record-storage-server/src/test/java/org/folio/services/handlers/AbstractPostProcessingEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/handlers/AuthorityPostProcessingEventHandlerTest.java
"PMSystem" displayed as source in "quickmarc" view when record was created by "Non-matches" action of job profile
MODSOURCE-608: Added user metadata during post processing
[MODSOURCE-608](https://folio-org.atlassian.net/browse/MODSOURCE-608)
=> MODSOURCE-608: Missing metadata in quick-marc editor

mod-source-record-storage-server/pom.xml, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDao.java, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/parser/SearchExpressionParser.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/parser/lexeme/operand/DateRangeBinaryOperand.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/parser/lexeme/operand/IndicatorBinaryOperand.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/parser/lexeme/operand/PositionBinaryOperand.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/parser/lexeme/operand/PresenceBinaryOperand.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/parser/lexeme/operand/SubFieldBinaryOperand.java, mod-source-record-storage-server/src/main/java/org/folio/services/util/parser/lexeme/operand/ValueBinaryOperand.java, mod-source-record-storage-server/src/test/java/org/folio/dao/RecordDaoImplTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceStorageStreamApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/SearchExpressionParserUnitTest.java
- changed the approach to refer to marc_indexers table. Previously, there have been used partitions of the marc_indexers table, and not to boiler-plate script with joins, there is introduced field number conditioning inside of search criteria.
- Due to complex structure of the criteria search, there are numerous cases which need to be considered, such as parenthesis included search. E.g., (050.a ^= 'a' and 050.b ^= 'b') or 050.c ^= 'c', or search criteria relates date search.
- Please notice TODO's in the java code.
- Main problem is to parse conditions with additional parenthesis to not break condition wholeness. There is a test which is ignored, due to the mentioned issue.
- Not added **marc_indexers** tracking, during the investigation no noticeable changes found after removing this …
=> MODSOURCE-763 SRS MARC query search won't allow you to create two search conditions for a single field (SPIKE)

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java, mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java
The 'No action' status is displayed in the 'SRS Marc' and 'Instance' columns after importing file for updating record on member tenant
Find record by match id instead record id
[MODSOURMAN-1200](https://folio-org.atlassian.net/browse/MODSOURMAN-1200)
=> MODSOURMAN-1200 Find record by match id instead record id

NEWS.md, mod-source-record-storage-server/src/main/java/org/folio/services/util/AdditionalFieldsUtil.java, mod-source-record-storage-server/src/test/java/org/folio/services/AdditionalFieldsUtilTest.java
[MODINV-1049](https://folio-org.atlassian.net/browse/MODINV-1049) Existing "035" field is not retained the original position in imported record
* fix replace old oclc 035 field with normalized data
* add test
=> MODINV-1049 Existing "035" field is not retained the original position in imported record

mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDao.java, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/match/AbstractMarcMatchEventHandler.java, mod-source-record-storage-server/src/test/java/org/folio/dao/RecordDaoImplTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/RecordsMatchingApiTest.java
Enhance implementation of /source-storage/records/matching endpoint to account for comparison part when building a search query to get the record for matching.
SQL query generation has been changed to take into account the new conditions
[MODSOURCE-787](https://folio-org.atlassian.net/browse/MODSOURCE-787)
=>  MODSOURCE-787: Extend MARC-MARC search query to account for comparison part

mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
Timeout exception during postSourceStorageStreamMarcRecordIdentifiers
Closing unused database connections.
[MODSOURCE-791](https://folio-org.atlassian.net/browse/MODSOURCE-791)
=> MODSOURCE-791: Timeout exception during postSourceStorageStreamMarcRecordIdentifiers

NEWS.md, descriptors/ModuleDescriptor-template.json, pom.xml
Permission refactoring
For each renamed permissions: Search for all `**/ModuleDescriptor*` and all `package.json` of other modules that contain them and ensure that a pull request exists that changes the name.
* "source-storage.snapshots.get" -> "source-storage.snapshots.collection.get", "source-storage.snapshots.item.get"
* "source-storage.records.get" -> "source-storage.records.collection.get", "source-storage.records.item.get", "source-storage.records.formatted.item.get", "source-storage.records.matching.collection.post", "source-storage.stream.records.collection.get",             "source-storage.stream.marc-record-identifiers.collection.post"
* "source-storage.records.put" ->             "source-storage.records.generation.item.put", …
=> MODSOURCE-796 Cleanup permissions

mod-source-record-storage-server/src/main/java/org/folio/services/handlers/links/UpdateLinkProcessor.java, mod-source-record-storage-server/src/test/java/org/folio/services/handlers/links/UpdateLinkProcessorTest.java
Fix bib fields order on link update event
- Handle only authority natural id change
- Put uncontroller alphabetic fields before controlled number fields
[MODSOURCE-842](https://folio-org.atlassian.net/browse/MODSOURCE-842)
=> fix(marc-fields-order): Fix bib fields order on link update event

NEWS.md, README.md, mod-source-record-storage-server/src/main/java/org/folio/consumers/AuthorityLinkChunkKafkaHandler.java, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/main/java/org/folio/dao/util/ParsedRecordDaoUtil.java, mod-source-record-storage-server/src/main/java/org/folio/services/RecordService.java, mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java
Handling Authority-Instance links event works well when having one consumer (module instance) of the event. 
When there are many events being received at the same time for the same instance and they are handled by two or more consumers / (running module instances) then one _silently_ overwrites the changes of another causing the updates being lost.
1. Change `srs.marc-bib` event's key from serial integer value to the instance id, so that in consuming side of this event (mod-inventory) only one consumer would be responsible to handle events for the same instance.
2. Do not make separate query to get value for `generation` column from `records_lb` as we have just made records read query and have `generation`'s value at the time of query. Having the separate query prevents to detect the …
=> MODSOURCE-832: In Handling Authority-Instance links events, make updating Bib fields consistent for having two or more event consumers.

mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDao.java, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/main/java/org/folio/verticle/MarcIndexersVersionDeletionVerticle.java, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-5.10.0/2024-12-10--20-00-create-delete-old-marc-indexers-versions.xml, mod-source-record-storage-server/src/test/java/org/folio/dao/RecordDaoImplTest.java, mod-source-record-storage-server/src/test/java/org/folio/verticle/MarcIndexersVersionDeletionVerticleMockTest.java, mod-source-record-storage-server/src/test/java/org/folio/verticle/MarcIndexersVersionDeletionVerticleTest.java
The first run of the process takes a very long time, and frequent startup puts a heavy load on the processor.
- The scheduled start parameter has been added: srs.marcIndexers.delete.plannedTime
- Periodic start parameter: srs.marcIndexers.delete.interval.seconds = 1800
- Added parameter to limit the number of records deleted at a time: srs.marcIndexers.delete.dirtyBatchSize = 100`000
To start a scheduled execution, specify plannedTime like 00:00 or a comma-separated list of values is supported: 01:00,02:30
[MODSOURCE-855](https://folio-org.atlassian.net/browse/MODSOURCE-855)
=> MODSOURCE-855: Error (No space left on device) during CALL delete_old_marc_indexers_versions

mod-source-record-storage-server/src/main/java/org/folio/consumers/AuthorityDomainKafkaHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/AbstractDeleteEventHandler.java, mod-source-record-storage-server/src/test/java/org/folio/consumers/AuthorityDomainKafkaHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcAuthorityDeleteEventHandlerTest.java
Update soft delete logic for Marc Authority
Use deleteRecordBy id for soft delete of authority
https://folio-org.atlassian.net/browse/MODSOURCE-854
=> [MODSOURCE-854] Use deleteRecordBy id for soft delete of authority

mod-source-record-storage-server/pom.xml, mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java, mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java
Update deleted markers when leader 05 value is changed during QuickMarc flow
if incoming leader is 'd' - mark record as deleted, otherwise mark record as actual
https://folio-org.atlassian.net/browse/MODSOURCE-760
=> [MODSOURCE-760] Update deleted markers when leader 05 value is changed during QuickMarc flow

NEWS.md, descriptors/ModuleDescriptor-template.json, mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageRecordsImpl.java, mod-source-record-storage-server/src/main/java/org/folio/services/RecordService.java, mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceRecordApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java, ramls/source-record-storage-records.raml
Undelete feature for records
API
=> MODSOURCE-859: Create new API POST /source-storage/records/{id}/un-delete

mod-source-record-storage-server/pom.xml, mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java, mod-source-record-storage-server/src/main/java/org/folio/dao/util/RecordDaoUtil.java, mod-source-record-storage-server/src/main/resources/liquibase/tenant/changelog.xml, mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-5.10.0/2025-22-04--15-00-update-composite-index-immutable-to-date-with-marc-id.xml, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceRecordApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceStorageStreamApiTest.java
Long-running query causing timeout on [POST] /source-storage/stream/marc-record-identifiers
Refactored query: 
- Join marc_records_tracking on version also to get latest versions
- Remove HAVING clause
- Use joins instead of subquery
- Select count from cte
Query example:
> with "filtered_records" as (
select
"records_lb"."external_id"
from
"records_lb"
join marc_indexers on "records_lb"."id" = marc_indexers.marc_id
join "marc_records_tracking" on (
"marc_records_tracking"."marc_id" = marc_indexers.marc_id
and "marc_records_tracking"."version" = marc_indexers.version
)
where
(
(
(
"field_no" = '005'
AND immutable_to_date(value) <= '20250512'
)
)
and (leader_record_status = 'd')
and "records_lb"."state" in ('ACTUAL', 'DELETED')
and "records_lb"."record_type" = 'MARC_BIB'
and …
=> [MODSOURCE-871] Optimize stream marc records id query

mod-source-record-storage-server/src/main/java/org/folio/dao/util/RecordDaoUtil.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceRecordApiTest.java
Revert filterRecordByDeleted to return ACTUAL records with deleted leader
Revert changes
=> [MODSOURCE-871] Revert filterRecordByDeleted to return ACTUAL records with deleted leader

mod-source-record-storage-server/pom.xml
[ERROR] Failed to execute goal dev.aspectj:aspectj-maven-plugin:1.14.1:compile (default) on project mod-source-record-storage-server: AJC compiler errors
bump aspectj-maven-plugin version to 1.14.1 and aspectj.version to 1.9.21
[MODSOURCE-915](https://folio-org.atlassian.net/browse/MODSOURCE-915)
=> MODSOURCE-914: Update aspectj-maven-plugin to version 1.14.1 and add support for java 21

mod-source-record-storage-server/pom.xml, mod-source-record-storage-server/src/main/java/org/folio/services/util/AdditionalFieldsUtil.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/RecordApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/RecordsGenerationTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/RecordsMatchingApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SnapshotApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceRecordApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceStorageBatchApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceStorageStreamApiTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/AuthorityLinkChunkKafkaHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcAuthorityUpdateModifyEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibUpdateModifyEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcHoldingsUpdateModifyEventHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/QuickMarcKafkaHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java, mod-source-record-storage-server/src/test/java/org/folio/verticle/MarcIndexersVersionDeletionVerticleTest.java, mod-source-record-storage-server/src/test/java/org/folio/verticle/consumers/DataImportConsumersVerticleTest.java
Version 2.9.6 deserializes NULL values in JSON to “\u0000”.
Fix tests: a few cases do not initialize the mandatory fields.
[MODSOURCE-914](https://folio-org.atlassian.net/browse/MODSOURCE-914)
=> MODSOURCE-914: Update marc4j for 2.9.6 version

mod-source-record-storage-server/pom.xml, mod-source-record-storage-server/src/main/java/org/folio/consumers/DataImportKafkaHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/AbstractUpdateModifyEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/MarcAuthorityUpdateModifyEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/MarcBibUpdateModifyEventHandler.java, mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/MarcHoldingsUpdateModifyEventHandler.java, mod-source-record-storage-server/src/test/java/org/folio/consumers/DataImportKafkaHandlerTest.java, mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibUpdateModifyEventHandlerTest.java
to prohibit MARC record update on a central tenant if user does not have appropriate permissions/capabilities
* check if user has "consortia.data-import.central-record-update.execute" permission allowing update of record on central tenant
* add tests
[MODSOURCE-919](https://issues.folio.org/browse/MODSOURCE-919)
=> MODSOURCE-919 - Ability to restrict record update action in member tenant to local record only

mod-source-record-storage-server/pom.xml, mod-source-record-storage-server/src/main/java/org/folio/verticle/consumers/AbstractConsumerVerticle.java
to configure "group.instance.id" parameter during consumer wrapper creation
[MODSOURCE-937](https://issues.folio.org/browse/MODSOURCE-937)
=> MODSOURCE-937 - Set groupInstanceId property during consumer wrapper creation
