NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
ramls/dto/record.json
ramls/dto/recordCollection.json
ramls/errorRecord.json
ramls/examples/record.sample
ramls/examples/recordCollection.sample
ramls/parsedRecord.json
ramls/recordModel.json
ramls/recordType.json
ramls/source-record-storage.raml
ramls/sourceRecord.json
src/main/java/org/folio/dao/RecordDao.java
src/main/java/org/folio/dao/RecordDaoImpl.java
src/main/java/org/folio/dao/SnapshotDaoImpl.java
src/main/java/org/folio/dao/util/DaoUtil.java
src/main/java/org/folio/rest/impl/SourceStorageImpl.java
src/main/java/org/folio/services/RecordService.java
src/main/java/org/folio/services/RecordServiceImpl.java
src/main/resources/templates/db_scripts/create_records_view.sql
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/rest/impl/AbstractRestVerticleTest.java
src/test/java/org/folio/rest/impl/RecordApiTest.java
src/test/java/org/folio/rest/impl/SnapshotApiTest.java

* Added schemas for Record entity
* Added tables for records, source_records, error_records, marc_records and the records_view to the db
* Defined endpoints for managing CRUD operations over Record entity
* Implemented the endpoints methods
* Created API tests for each added endpoint

MODSOURCE-7 Added CRUD API for Record entities

---

NEWS.md
descriptors/ModuleDescriptor-template.json
pom.xml
ramls/dto/result.json
ramls/dto/resultCollection.json
ramls/examples/result.sample
ramls/examples/resultCollection.sample
ramls/source-record-storage.raml
src/main/java/org/folio/dao/RecordDao.java
src/main/java/org/folio/dao/RecordDaoImpl.java
src/main/java/org/folio/rest/impl/SourceStorageImpl.java
src/main/java/org/folio/services/RecordService.java
src/main/java/org/folio/services/RecordServiceImpl.java
src/main/resources/templates/db_scripts/create_records_view.sql
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/rest/impl/AbstractRestVerticleTest.java
src/test/java/org/folio/rest/impl/RecordApiTest.java
src/test/java/org/folio/rest/impl/SnapshotApiTest.java

* Added schema for Result entity
* Added results_view to the db
* Defined endpoint for GETting the results
* Implemented the endpoint
* Created API tests for the added endpoint

MODSOURCE-8 Added GET endpoint for Result entity

---

src/main/java/org/folio/dao/RecordDaoImpl.java
src/main/java/org/folio/dao/SnapshotDaoImpl.java
src/main/java/org/folio/dao/util/RecordType.java
src/main/java/org/folio/rest/impl/SourceStorageImpl.java
src/main/resources/templates/db_scripts/create_records_view.sql
src/main/resources/templates/db_scripts/schema.json
src/test/java/org/folio/rest/impl/RecordApiTest.java

Bug fix: added metadata to Result and Record

MODSOURCE-13 Add metadata to Result

---

NEWS.md

test lint-raml and re-do generate-api-docs

FOLIO-903 apidocs config

---

mod-source-record-storage-client/pom.xml
mod-source-record-storage-server/pom.xml
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/TestMarcRecordsApiTest.java
pom.xml

fix smells

---

mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/RecordApiTest.java

-changed sql query to increase fetching source records

MODSOURCE-47 Slow queries with 25k source records

---

NEWS.md
mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
mod-source-record-storage-server/src/main/resources/templates/db_scripts/create_records_view.sql
mod-source-record-storage-server/src/main/resources/templates/db_scripts/schema.json
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/RecordApiTest.java

Added indexes for source record view in the records, raw_records, marc_records tables

Modsource 48

---

NEWS.md
descriptors/ModuleDescriptor-template.json
mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDao.java
mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageImpl.java
mod-source-record-storage-server/src/main/java/org/folio/services/RecordService.java
mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/RecordApiTest.java
ramls/source-record-storage.raml

Checked locally - endpoint works as expected

MODSOURCE-52 Added batch PUT endpoint for updating parsed records

---

descriptors/ModuleDescriptor-template.json
mod-source-record-storage-server/pom.xml
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageBatchImpl.java
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageImpl.java
mod-source-record-storage-server/src/main/java/org/folio/services/RecordService.java
mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/RecordApiTest.java
ramls/source-record-storage-batch.raml
ramls/source-record-storage.raml

-added errorMessages to the recordCollection DTO
-turned on auto generation of equals and hashCode in DTOs
-updated raml-storage
-fixed tests

Modsource 55

---

NEWS.md
descriptors/ModuleDescriptor-template.json
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageBatchImpl.java
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageImpl.java
mod-source-record-storage-server/src/main/java/org/folio/services/RecordService.java
mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/RecordApiTest.java
ramls/source-record-storage-batch.raml
ramls/source-record-storage.raml

-moved source-storsge/parsedRecordsCollection to a separate interface for batch operations
-added error messages to a response if any records were not updated

MODSOURCE-56 Partial batch update for parsed records

---

mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/RecordApiTest.java
ramls/source-record-storage.raml

For RecordServiceImpl and RecordApiTest only indentation was changed, please do not review

MODSOURCE-65 Updated populate-test-marc-records endpoint description

---

NEWS.md
mod-source-record-storage-client/pom.xml
mod-source-record-storage-server/pom.xml
pom.xml

Tmp release 2.5.0

---

mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageBatchImpl.java
mod-source-record-storage-server/src/main/java/org/folio/services/RecordService.java
mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/RecordApiTest.java
ramls/source-record-storage-batch.raml

-changed recordCollection to recordBatch schemas for POST batch records

MODSOURCE-67 Remove 'errorMessages' from response to get records

---

descriptors/ModuleDescriptor-template.json

Endpoint w/o required permissions

MODSOURCE-78 Endpoint w/o required permissions

---

NEWS.md
mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/RecordsGenerationTest.java

I Added check for calculate generation (if generation==null) and added one test that checks this.

Modsource-107 Add check for calculate generation

---

mod-source-record-storage-server/src/main/java/org/folio/services/CreatedInstanceEventHandlingServiceImpl.java
mod-source-record-storage-server/src/test/java/org/folio/services/CreatedInstanceEventHandlingServiceImplTest.java
pom.xml

1. Unzipping mechanism added.
2. "data-import-processing-core" was added to the pom.xml.

MODSOURCE-118: Archive event payload.

---

mod-source-record-storage-server/src/main/java/org/folio/services/CreatedInstanceEventHandlingServiceImpl.java
mod-source-record-storage-server/src/test/java/org/folio/services/CreatedInstanceEventHandlingServiceImplTest.java
pom.xml

Revert "MODSOURCE-118: Archive event payload. (#128)"

---

NEWS.md
mod-source-record-storage-server/src/main/resources/templates/db_scripts/migration_scripts/records_add_actual_state.sql
mod-source-record-storage-server/src/main/resources/templates/db_scripts/schema.json

1. New script added.
2. NEWS.md updated.

MODSOURCE-126: Add State "field" to migration script.

---

NEWS.md
mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/ModTenantAPI.java
mod-source-record-storage-server/src/main/resources/templates/db_scripts/create_get_record_by_id_function.sql
mod-source-record-storage-server/src/main/resources/templates/db_scripts/schema.json
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/RecordApiTest.java
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/RecordsGenerationTest.java
mod-source-record-storage-server/src/test/java/org/folio/services/CreatedInstanceEventHandlingServiceImplTest.java

(cherry picked from commit 51dfcfe39d723655635fa4aff7cf7f2de951f32f)

MODSOURCE-114: Add State "field" to records table. (#131)

---

NEWS.md
mod-source-record-storage-server/src/main/java/org/folio/services/CreatedInstanceEventHandlingServiceImpl.java
mod-source-record-storage-server/src/test/java/org/folio/services/CreatedInstanceEventHandlingServiceImplTest.java
pom.xml

1. Zipping and unzipping added.
2. di-core version bumped up to "2.1.0-SNAPSHOT".
3. Tests added.

MODSOURCE-124: Apply archive/unarchive eventPayload mechanism

---

mod-source-record-storage-server/src/main/java/org/folio/dao/PostgresClientFactory.java

Vert.x single thread model ensures this to not have race condition.

MODSOURCE-138: remove synchronized when getting PgPool

---

mod-source-record-storage-server/src/main/resources/MessagingDescriptor.json

A workaround to allow SRS to register in pubsub before mod-inventory

MODSOURCE-142 Defined DI_INVENTORY_INSTANCE_CREATED and DI_COMPLETED event types

---

NEWS.md
mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
mod-source-record-storage-server/src/main/java/org/folio/dao/util/ParsedRecordDaoUtil.java
mod-source-record-storage-server/src/main/java/org/folio/dao/util/RecordDaoUtil.java
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageSourceRecordsImpl.java
mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-0.0.2/2020-06-11--13-00-create-records-table.xml
mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-0.0.2/2020-06-11--15-00-create-marc-records-table.xml
mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-0.0.2/2020-06-12--13-00-migrate-records.xml
mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-0.0.2/2020-06-12--15-00-migrate-marc-records.xml
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceRecordApiTest.java
mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java
mod-source-record-storage-server/src/test/resources/mock/records/0f0fe962-d502-4a4f-9e74-7732bec94ee8.json
mod-source-record-storage-server/src/test/resources/mock/records/4c0ff739-3f4d-4670-a693-84dd48e31c53.json
mod-source-record-storage-server/src/test/resources/mock/records/7293f287-bb51-41f5-805d-00ff18a1f791.json
mod-source-record-storage-server/src/test/resources/mock/records/8452daf9-c130-4955-99ce-1c397a218900.json
mod-source-record-storage-server/src/test/resources/mock/records/8f462542-387c-4f06-a01b-50829c7c7b13.json
mod-source-record-storage-server/src/test/resources/mock/records/8fb19e31-0920-49d7-9438-b573c292b1a6.json
mod-source-record-storage-server/src/test/resources/mock/records/be1b25ae-4a9d-4077-93e6-7f8e59efd609.json
mod-source-record-storage-server/src/test/resources/mock/records/d3cd3e1e-a18c-4f7c-b053-9aa50343394e.json
mod-source-record-storage-server/src/test/resources/mock/records/e567b8e2-a45b-45f1-a85a-6b6312bdf4d8.json
mod-source-record-storage-server/src/test/resources/mock/records/ec53a386-9616-428b-92a9-e1f07756ea1f.json
ramls/source-record-storage-source-records.raml

https://issues.folio.org/browse/MODSOURCE-157
This is fast forward from https://github.com/folio-org/mod-source-record-storage/pull/185 to avoid conflicts.

MODSOURCE-157: Get source records filter by record state

---

mod-source-record-storage-server/pom.xml
pom.xml

This will fix client generation to support date time.

RMB upgrade to 30.2.0

---

mod-source-record-storage-client/src/main/java/org/folio/rest/client/SourceStorageSourceRecordsClient.java

Fixes date formats in SRS client

Fix date format

---

mod-source-record-storage-client/src/main/java/org/folio/rest/client/SourceStorageSourceRecordsClient.java

This should resolve [MODSOURCE-163](https://issues.folio.org/browse/MODSOURCE-163)
Here is the [PR for RMB](https://github.com/folio-org/raml-module-builder/pull/721) for next release to replace clients with generated clients.

MODSOURCE-163: Use UTC instead of system default

---

NEWS.md
mod-source-record-storage-server/src/main/java/org/folio/dao/util/RecordDaoUtil.java
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageSourceRecordsImpl.java
mod-source-record-storage-server/src/main/resources/liquibase/tenant/changelog.xml
mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-0.0.2/2020-09-01--13-00-create-instance-hrid-column.xml
mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-0.0.2/2020-09-01--14-00-migrate-instance-hrid.xml
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceRecordApiTest.java
ramls/source-record-storage-source-records.raml

1. "instanceHrid" added as parameter to endpoint.
2. Filtering by "instanceHrid" added.

MODDICORE-58: MARC-MARC matching for 001 and 999 ff fields.

---

mod-source-record-storage-server/src/main/java/org/folio/rest/impl/ModTenantAPI.java
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageHandlersImpl.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/ModifyRecordEventHandler.java
mod-source-record-storage-server/src/main/java/org/folio/services/util/AdditionalFieldsUtil.java
mod-source-record-storage-server/src/test/java/org/folio/services/ModifyRecordEventHandlerTest.java

MODSOURMAN-249
HRID/001/003 handling in SRS for MARC bib records: Modify/Update

MODSOURMAN-249 HRID/001/003 handling in SRS for MARC bib records: Modify/Update

---

NEWS.md
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/MarcBibliographicMatchEventHandler.java
mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibliographicMatchEventHandlerTest.java

1. Bug fixed.
2. Test added.
3. NEWS updated.

MODDSOURCE-186: Job status is "Completed with errors" when holding updating [BUGFIX]

---

mod-source-record-storage-client/pom.xml
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/InstancePostProcessingEventHandler.java

1. Changes for 001 field reverted.

MODDICORE-58: MARC-MARC matching for 001 and 999 ff fields

---

NEWS.md
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/MarcBibliographicMatchEventHandler.java
mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibliographicMatchEventHandlerTest.java

1. Additional filter by ACTUAL state added.
2. Test added.
3. NEWS updated.

MODSOURCE-212: Update MARC record with field protections - job failed.

---

NEWS.md
mod-source-record-storage-server/src/main/java/org/folio/services/exceptions/PostProcessingException.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/InstancePostProcessingEventHandler.java
mod-source-record-storage-server/src/test/java/org/folio/services/InstancePostProcessingEventHandlerTest.java

1. Mechanism added: for non-match case, after instance updated in SRS check if exist marc record. If not - create and link to the instance (999, hrid, etc).
2. Tests added.
3. NEWS updated.

MODSOURMAN-385: Enable OCLC update processing.

---

NEWS.md
mod-source-record-storage-server/src/main/java/org/folio/services/util/AdditionalFieldsUtil.java
mod-source-record-storage-server/src/test/java/org/folio/services/InstancePostProcessingEventHandlerTest.java

1. Additional check added. It will fill 001 field if it hrid exists.
2. NEWS updated.

MODSOURCE-217: If incoming MARC bib lacks 001, sometimes it is added and sometimes not.[BUGFIX]

---

NEWS.md
mod-source-record-storage-server/src/main/resources/liquibase/tenant/changelog.xml
mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-0.0.2/2021-01-11--12-00-drop-set-id-in-jsonb-function.xml

1. Script for removing set_id_in_jsonb() added.
2. NEWS updated.

MODSOURCE-220: Migration script between Goldenrod-hotfix-5 and Honeysuckle.

---

mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java

Suppress from discovery update is not reflected in SRS
Add AdditionalInfo to store the missing setting

fix suppress from discovery issue

---

NEWS.md
PERSONAL_DATA_DISCLOSURE.md

Add personal data disclosure resolved [MODSOURCE-225](https://issues.folio.org/browse/MODSOURCE-225)
N/A
N/A

MODSOURCE-225: add personal data disclosure

---

mod-source-record-storage-server/src/main/java/org/folio/verticle/consumers/DataImportConsumersVerticle.java

ConsumersVerticle start and stop futures complete multiple times
Use Composite future

Fix multiple completion of the same future

---

descriptors/ModuleDescriptor-template.json
mod-source-record-storage-server/src/main/java/org/folio/config/ApplicationConfig.java
mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/AbstractRestVerticleTest.java
mod-source-record-storage-server/src/test/java/org/folio/services/AbstractLBServiceTest.java

Set correct env variables names for kafka config

Fix names for required kafka variables

---

mod-source-record-storage-server/pom.xml
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/AbstractRestVerticleTest.java
mod-source-record-storage-server/src/test/java/org/folio/services/AbstractLBServiceTest.java

Tests fixed.

---

mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDao.java
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/AbstractRestVerticleTest.java
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/RecordApiTest.java
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceRecordApiTest.java
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceStorageBatchApiTest.java
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceStorageStreamApiTest.java
mod-source-record-storage-server/src/test/java/org/folio/services/AbstractLBServiceTest.java
mod-source-record-storage-server/src/test/java/org/folio/services/InstancePostProcessingEventHandlerTest.java
mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibliographicMatchEventHandlerTest.java

Fixes some tests ignored due to test dependency object mapper deserializing maps incorrectly.

Some test fixes

---

NEWS.md
mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
mod-source-record-storage-server/src/main/java/org/folio/services/ParsedRecordChunksKafkaHandler.java
mod-source-record-storage-server/src/test/java/org/folio/verticle/consumers/ParsedRecordChunkConsumersVerticleTest.java

avoid data import hanging if error occured on records saving
* take into account saved records from failed data import (snapshot.status = 'error') on generation calculation
* send event with necessary data for import progress handling and writing to data-imp log when records saving failed
[MODSOURCE-278](https://issues.folio.org/browse/MODSOURCE-278)

MODSOURCE-278 - Record from chunk is not saved occasionally

---

README.md

MODDATAIMP-431: Update module readme files to reflect Iris environment variables.

---

NEWS.md
descriptors/ModuleDescriptor-template.json

Due to changes made in scope of https://issues.folio.org/browse/MODSOURCE-279 interfaces version should be updated to notify dependant modules about changes. 
* updated interface version for:
- "source-storage-records"
- "source-storage-source-records"
from 2.0 to 3.0

MODSOURCE-308 - Update interfaces version

---

NEWS.md
descriptors/ModuleDescriptor-template.json

Revert "MODSOURCE-308 - Update interfaces version (#341)"

---

mod-source-record-storage-server/pom.xml

MODDPUBSUB-181: Update folio-kafka-wrapper version to 2.4.0-SNAPSHOT

---

mod-source-record-storage-server/pom.xml

MODPUBSUB-181: Bump folio-kafka-wrapper to 2.3.1

---

mod-source-record-storage-server/src/main/java/org/folio/services/QuickMarcKafkaHandler.java
mod-source-record-storage-server/src/main/java/org/folio/services/util/EventHandlingUtil.java

Change quickMarc producers not to close after message sent
* Create shared producers and store them in map
* Do not close producer after message sent

MODSOURCE-337 Change QM producers not to close after message sent

---

NEWS.md
mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-0.0.2/2020-09-09--15-00-fill-instance-hrid.xml

Move code from ticket https://issues.folio.org/browse/MODSOURCE-357 to release branch

MODSOURCE-357. Improve "fill-instance-hrid" script... to release branch

---

mod-source-record-storage-server/src/main/java/org/folio/services/QuickMarcKafkaHandler.java

Fix quickMarc payload
* Change key of marc record

MODINV-473 Fix QM update payload

---

mod-source-record-storage-server/src/main/java/org/folio/rest/impl/InitAPIImpl.java

Register holdingsPostProcessingEventHandler

MODSOURCE-376 Register holdingsPostProcessingEventHandler

---

NEWS.md
mod-source-record-storage-client/pom.xml
mod-source-record-storage-server/pom.xml
mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceStorageStreamApiTest.java
pom.xml

Release/2021 r3 v5.2.2 kiwi

---

NEWS.md
mod-source-record-storage-server/pom.xml
mod-source-record-storage-server/src/main/java/org/folio/dao/PostgresClientFactory.java
mod-source-record-storage-server/src/test/resources/postgres-conf-test.json
pom.xml

Log4j vulnerability verification and correction
upgrade log4j to 2.16.0
https://issues.folio.org/browse/MODSOURCE-425

MODSOURCE-425: Log4j vulnerability verification and correction

---

NEWS.md
mod-source-record-storage-server/src/main/java/org/folio/dao/PostgresClientFactory.java
mod-source-record-storage-server/src/test/resources/postgres-conf-test.json
pom.xml

MODSOURCE-421: Add possibility to adjust parameter DB_MAXPOOLSIZE for configuring connection pool
MODSOURCE-422: Upgrade Vertx from 4.0.0 to 4.1.2
Add support for the existing RMB parameter DB_MAXPOOLSIZE
Upgrade Vertx from 4.0.0 to 4.1.2
https://issues.folio.org/browse/MODSOURCE-421
https://issues.folio.org/browse/MODSOURCE-422

Fix OOM in Juniper HF4

---

mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-0.0.3/2021-02-13--12-00-create-fill-in-trigger.xml

Fix Schema migration error when upgrading from Juniper hotfix 4.3 to Kiwi-GA

MODSOURCE-444 Schema migration error when upgrading from Juniper hotfix 4.3 to Kiwi-GA

---

mod-source-record-storage-server/pom.xml
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/InitAPIImpl.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/AbstractPostProcessingEventHandler.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/AuthorityPostProcessingEventHandler.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/HoldingsPostProcessingEventHandler.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/InstancePostProcessingEventHandler.java
mod-source-record-storage-server/src/main/java/org/folio/services/util/AdditionalFieldsUtil.java
mod-source-record-storage-server/src/main/java/org/folio/verticle/consumers/DataImportConsumersVerticle.java
mod-source-record-storage-server/src/test/java/org/folio/services/handlers/AuthorityPostProcessingEventHandlerTest.java

Add Authority post-processing hadler

MODSOURCE-449 Add Authority post-processing hadler

---

mod-source-record-storage-server/src/main/java/org/folio/services/handlers/InstancePostProcessingEventHandler.java

Log displays incorrect response when using Update action to create new instances for non-matches
Send log event for DI_INVENTORY_INSTANCE_CREATED_READY_FOR_POST_PROCESSING

MODSOURCE-448 Fix incorrect data-import log

---

mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java

[MODSOURCE-437](https://issues.folio.org/browse/MODSOURCE-437)

MODSOURCE-437 - Fixed RecordsService tests

---

mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/AbstractUpdateModifyEventHandler.java

Error while importing file with expected update and create:
io.vartex.pgclient.PgException: ERROR:  current transaction is aborted, commands ignored until end of transaction block(25P02)
[MODDATAIMP-645](https://issues.folio.org/browse/MODDATAIMP-645)

MODDATAIMP-645 fix update a MARC authority record multiple times

---

mod-source-record-storage-server/pom.xml

Update version of data-import-processing-core to support "hidden" field in profiles
https://issues.folio.org/browse/MODSOURCE-476

MODSOURCE-476: Update version of data-import-processing-core

---

NEWS.md
mod-source-record-storage-server/src/main/resources/liquibase/tenant/changelog.xml
mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-5.4.0/2022-21-04--16-00-extend-snapshot-status-enum.xml

Added new status "CANCELLED" for job that are stopped by users manually.
Extended mechanism for status and ui-status execution
https://issues.folio.org/browse/MODSOURMAN-779

MODSOURMAN-779: Add status for Import jobs that are stopped by users.

---

NEWS.md
mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibUpdateModifyEventHandlerTest.java
mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java

Alleviate eventloop blocking during batch record saves
move blocking actions to be executed by worker threads
https://issues.folio.org/browse/MODSOURCE-499

MODSOURCE-499 fix eventloop blocking during batch records save

---

mod-source-record-storage-server/src/main/java/org/folio/consumers/DataImportKafkaHandler.java
mod-source-record-storage-server/src/main/java/org/folio/consumers/ParsedRecordChunksKafkaHandler.java

- Add metadata with user id while saving records
https://issues.folio.org/browse/MODSOURCE-514

MODSOURCE-514 Populate createdByUserId while creating marc record

---

mod-source-record-storage-server/pom.xml

https://issues.folio.org/browse/MODSOURCE-519

MODSOURCE-519: Remove org.json:json, license is not open source

---

mod-source-record-storage-server/src/main/java/org/folio/services/RecordService.java
mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/AbstractPostProcessingEventHandler.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/AuthorityPostProcessingEventHandler.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/HoldingsPostProcessingEventHandler.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/InstancePostProcessingEventHandler.java
mod-source-record-storage-server/src/test/java/org/folio/services/handlers/AbstractPostProcessingEventHandlerTest.java
mod-source-record-storage-server/src/test/java/org/folio/services/handlers/AuthorityPostProcessingEventHandlerTest.java
mod-source-record-storage-server/src/test/java/org/folio/services/handlers/HoldingsPostProcessingEventHandlerTest.java
mod-source-record-storage-server/src/test/java/org/folio/services/handlers/InstancePostProcessingEventHandlerTest.java

to calculate generation along with saving incoming record on instance update post-processing if the incoming record has matchedId same as an existing record
[MODINV-686](https://issues.folio.org/browse/MODINV-686)

MODINV-686 - Calculate generation while saving record on instance post-processing

---

mod-source-record-storage-server/src/main/java/org/folio/services/handlers/AbstractPostProcessingEventHandler.java

035 field with HRID, created after updating Marc Bib when updating with instance profile
Delete 035 field if it contains HRID
[MODSOURCE-528](https://issues.folio.org/browse/MODSOURCE-528)

MODSOURCE-528: Removing field 035 with HRID when updating Marc Bib with an instance update profile

---

PULL_REQUEST_TEMPLATE.md
mod-source-record-storage-server/src/main/resources/log4j2.properties
mod-source-record-storage-server/src/test/resources/log4j2-test.properties

Logging improvement - Configuration
Jira: https://issues.folio.org/browse/MODSOURCE-557

[MODSOURCE-557] Logging improvement - configuration

---

mod-source-record-storage-server/src/main/java/org/folio/config/ApplicationConfig.java
mod-source-record-storage-server/src/main/java/org/folio/consumers/DataImportKafkaHandler.java
mod-source-record-storage-server/src/main/java/org/folio/consumers/ParsedRecordChunksKafkaHandler.java
mod-source-record-storage-server/src/main/java/org/folio/consumers/QuickMarcKafkaHandler.java
mod-source-record-storage-server/src/main/java/org/folio/dao/PostgresClientFactory.java
mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
mod-source-record-storage-server/src/main/java/org/folio/errorhandlers/ParsedRecordChunksErrorHandler.java
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/InitAPIImpl.java
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/ModTenantAPI.java
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageBatchImpl.java
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStoragePopulateTestMarcRecordsImpl.java
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageRecordsImpl.java
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageSnapshotsImpl.java
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageSourceRecordsImpl.java
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageStreamImpl.java
mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java
mod-source-record-storage-server/src/main/java/org/folio/services/SnapshotRemovalServiceImpl.java
mod-source-record-storage-server/src/main/java/org/folio/services/caches/JobProfileSnapshotCache.java
mod-source-record-storage-server/src/main/java/org/folio/services/caches/MappingParametersSnapshotCache.java
mod-source-record-storage-server/src/main/java/org/folio/services/cleanup/RecordCleanupService.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/AbstractPostProcessingEventHandler.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/AbstractDeleteEventHandler.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/AbstractUpdateModifyEventHandler.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/match/AbstractMarcMatchEventHandler.java
mod-source-record-storage-server/src/main/java/org/folio/services/util/AdditionalFieldsUtil.java
mod-source-record-storage-server/src/main/java/org/folio/services/util/EventHandlingUtil.java

Logging improvement
Jira: https://issues.folio.org/browse/MODSOURCE-465

[MODSOURCE-465] Logging improvement

---

mod-source-record-storage-server/src/main/resources/log4j2-json.properties
mod-source-record-storage-server/src/test/resources/log4j2-test.properties

Adjust logging configuration to display datetime in a proper format
Changed configuration

[MODDATAIMP-736] Adjust logging configuration for SRS to display datetime in a proper format

---

mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDao.java
mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageSourceRecordsImpl.java
mod-source-record-storage-server/src/main/java/org/folio/rest/util/QueryParamUtil.java
mod-source-record-storage-server/src/main/java/org/folio/services/RecordService.java
mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java
mod-source-record-storage-server/src/test/java/org/folio/rest/impl/SourceRecordApiTest.java
mod-source-record-storage-server/src/test/java/org/folio/rest/util/QueryParamUtilTest.java
mod-source-record-storage-server/src/test/java/org/folio/services/MarcAuthorityDeleteEventHandlerTest.java
mod-source-record-storage-server/src/test/java/org/folio/services/QuickMarcKafkaHandlerTest.java
mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java
ramls/source-record-storage-source-records.raml

- merge feature branch to master
This branch contains this changes:
https://issues.folio.org/browse/MODSOURCE-552

MODSOURCE-552 Extend GET /source-storage/source-records/<Id> to fetch deleted record

---

mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
mod-source-record-storage-server/src/main/java/org/folio/dao/SnapshotDaoImpl.java

Improve logging in DAO
Added logs on trace level

[MODSOURCE-566] Improve logging in DAO

---

mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/AbstractUpdateModifyEventHandler.java
mod-source-record-storage-server/src/main/java/org/folio/services/util/AdditionalFieldsUtil.java

- Normalize parsed record content
- Use vertx Json to decode record as in other handlers

Modsource 569 - Error during the transformation to marc record

---

mod-source-record-storage-server/src/main/java/org/folio/consumers/AuthorityLinkChunkKafkaHandler.java
mod-source-record-storage-server/src/main/java/org/folio/services/util/EventHandlingUtil.java
mod-source-record-storage-server/src/main/java/org/folio/verticle/consumers/AuthorityLinkChunkConsumersVerticle.java
mod-source-record-storage-server/src/test/java/org/folio/services/AuthorityLinkChunkKafkaHandlerTest.java
mod-source-record-storage-server/src/test/java/org/folio/services/util/EventHandlingUtilTest.java

Fix consuming and producing
- remove "nameSpace" from consumer pattern and producer topic
[MODSOURCE-571](https://issues.folio.org/browse/MODSOURCE-571)

MODSOURCE-571 links.instance-authority event not being consumed

---

descriptors/ModuleDescriptor-template.json

Fix instance-authority-links dependency

---

mod-source-record-storage-server/pom.xml
mod-source-record-storage-server/src/main/java/org/folio/consumers/AuthorityLinkChunkKafkaHandler.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/links/DeleteLinkProcessor.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/links/LinkProcessor.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/links/UpdateLinkProcessor.java
mod-source-record-storage-server/src/test/java/org/folio/services/handlers/links/DeleteLinkProcessorTest.java
mod-source-record-storage-server/src/test/java/org/folio/services/handlers/links/UpdateLinkProcessorTest.java

Order subfields when update linked subfields
* Use TreeMap with comparator
* Make inner classes to standard classes for easy testing 

MODSOURCE-583 Order subfields when update linked subfields

---

mod-source-record-storage-server/src/main/java/org/folio/client/InstanceLinkClient.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/AbstractUpdateModifyEventHandler.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/MarcBibUpdateModifyEventHandler.java
mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibUpdateModifyEventHandlerTest.java

Fix unable to update "MARC Bib" record upon data import

MODSOURCE-586 Fix unable to update "MARC Bib" record upon data import

---

mod-source-record-storage-server/pom.xml
pom.xml

Update dependencies
Bumped dependencies version

[MODDATAIMP-750] Update dependencies

---

mod-source-record-storage-server/pom.xml

Change data-import-processing-core version to SNAPSHOT in order to have the latest changes
Change data-import-processing-core version from 4.0.0 to 4.1.0-SNAPSHOT

Change data-import-processing-core version to SNAPSHOT in order to have the latest changes

---

mod-source-record-storage-server/pom.xml

Update data-import-processing-core dependency
Updated data-import-processing-core dependency

[MODDICORE-306] Update data-import-processing-core dependency

---

mod-source-record-storage-server/pom.xml
mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibUpdateModifyEventHandlerTest.java

Fix test failures
Update tests according to mod-data-import-processing-core updates (MODDICORE-309, MODDICORE-311)
[MODDICORE-309](https://issues.folio.org/browse/MODDICORE-309)
[MODDICORE-311](https://issues.folio.org/browse/MODDICORE-311)

Update tests according to mod-data-import-processing-core updates (MODDICORE-309, MODDICORE-311)

---

NEWS.md
mod-source-record-storage-client/pom.xml
mod-source-record-storage-server/pom.xml
mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibUpdateModifyEventHandlerTest.java
pom.xml

Release v5.6.1 with updated data-import-processing-core
[MODSOURCE-596](https://issues.folio.org/browse/MODSOURCE-596)

MODSOURCE-596 Release mod-source-record-storage v5.6.1 Orchid Bug Fix (R1 2023)

---

mod-source-record-storage-server/src/main/java/org/folio/consumers/AuthorityLinkChunkKafkaHandler.java
mod-source-record-storage-server/src/main/java/org/folio/consumers/DataImportKafkaHandler.java
mod-source-record-storage-server/src/main/java/org/folio/consumers/ParsedRecordChunksKafkaHandler.java
mod-source-record-storage-server/src/main/java/org/folio/services/util/KafkaUtil.java
mod-source-record-storage-server/src/test/java/org/folio/services/AuthorityLinkChunkKafkaHandlerTest.java

Set updatedBy metadata on handling links update
Extract user id from kafka message headers and set it to each of updated records

MODSOURCE-603 Set updatedBy metadata on handling links update

---

mod-source-record-storage-server/src/main/java/org/folio/services/util/KafkaUtil.java

Use equalsIgnoreCase to extract headers from message

MODSOURCE-603 Use equalsIgnoreCase to extract headers from message

---

NEWS.md
mod-source-record-storage-server/src/main/resources/liquibase/tenant/changelog.xml
mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-5.6.3/2023-03-22--16-00-create-marc-indexers-010-value-index.xml
mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-5.6.3/2023-03-22--16-00-create-marc-indexers-value-index.xml
mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-5.6.3/2023-03-24--16-00-create-marc-indexers-035-value-index.xml

Brand new indices for marc_indexers_value added(010 and 035 fields).
This index will increase performance for the MARC_Authorities data import.
JIRA: https://issues.folio.org/browse/MODSOURCE-615

MODSOURCE-615: Added indexes for 010 and 035 fields

---

mod-source-record-storage-server/src/main/java/org/folio/dao/PostgresClientFactory.java

to make connection pull timeout configurable
[MODSOURCE-618](https://issues.folio.org/browse/MODSOURCE-618)

MODSOURCE-618 - Added DB_CONNECTION_TIMEOUT env variable to make pull timeout configurable

---

descriptors/ModuleDescriptor-template.json

Update ModuleDescriptor-template.json
Update ModuleDescriptor-template.json

MODSOURCE-609 Update links interactions according to 'instance-authority-links' interface change to 2.0

---

mod-source-record-storage-client/pom.xml
mod-source-record-storage-server/pom.xml
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageRecordsImpl.java
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageSnapshotsImpl.java
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageSourceRecordsImpl.java
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageStreamImpl.java
ramls/source-record-storage-records.raml
ramls/source-record-storage-snapshots.raml
ramls/source-record-storage-source-records.raml

MODSOURCE-632 Update action profile schema

---

mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-5.7.0/2023-04-13--16-00-update-fill-in-trigger.xml

old indexes don't remove 
schema name was added

MODSOURCE-601-1: added schema name to 'drop index'

---

mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
mod-source-record-storage-server/src/main/java/org/folio/dao/util/MatchField.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/match/AbstractMarcMatchEventHandler.java
mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibliographicMatchEventHandlerTest.java

Add support for matching for repeatable marc fields
Added support of matching repeatable 035 fields (any incoming field to any existing field)
Jira: https://issues.folio.org/browse/MODSOURCE-644

[MODSOURCE-644] Add support for matching for repeatable marc fields

---

mod-source-record-storage-server/pom.xml
mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java
mod-source-record-storage-server/src/test/java/org/folio/services/handlers/links/DeleteLinkProcessorTest.java
mod-source-record-storage-server/src/test/java/org/folio/services/handlers/links/UpdateLinkProcessorTest.java
mod-source-record-storage-server/src/test/java/org/folio/services/util/EventHandlingUtilTest.java
mod-source-record-storage-server/src/test/java/org/folio/verticle/consumers/ParsedRecordChunkConsumersVerticleTest.java

Allow tests to run on M1 Mac workstations

allow tests to run on M1 Mac

---

mod-source-record-storage-server/pom.xml

The main purpose it to update link on the raml-storage to provide all needed schemas for Wrappers-feature.
JIRA: https://issues.folio.org/browse/MODDICONV-310

MODDICONV-310: Wrappers Feature.

---

mod-source-record-storage-server/pom.xml
mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java
mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java

The import of .edi file is completed with errors
Not add 999 field to EDIFACT record during set of matchedId

[MODSOURCE-700] Not add 999 field to EDIFACT record during set of matchedId

---

mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/MarcBibUpdateModifyEventHandler.java

Links are not updated if the shared bib updated via data import from member tenant
Change API calls to the central tenant for shared BIB

MODSOURCE-715 Change API calls to central tenant for shared BIB

---

mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
mod-source-record-storage-server/src/test/java/org/folio/dao/RecordDaoImplTest.java

when records with 010 $ a already present mod-srs thrown an exception **org.folio.processing.exceptions.MatchingException: Found multiple records matching specified conditions** Hot fix for this issue
[MODSOURCE-709](https://issues.folio.org/browse/MODSOURCE-709)
Return empty list if value field doesn't have a any value

FIX FOR MODSOURCE-709

---

mod-source-record-storage-server/src/main/java/org/folio/consumers/ParsedRecordChunksKafkaHandler.java
mod-source-record-storage-server/src/main/java/org/folio/consumers/QuickMarcKafkaHandler.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/match/AbstractMarcMatchEventHandler.java
mod-source-record-storage-server/src/test/java/org/folio/services/MarcBibliographicMatchEventHandlerTest.java

added handling of potential unhandled errors while creating java object from json
[MODSOURMAN-1109](https://issues.folio.org/browse/MODSOURMAN-1109)

MODSOURMAN-1109 - Fix all the places in the code where a Java object is instantiated from a JsonObject

---

mod-source-record-storage-server/src/main/java/org/folio/verticle/consumers/DataImportConsumersVerticle.java

Fix stuck of MARC Bib modify
Register DI_INCOMING_MARC_BIB_RECORD_PARSED for MARC Bib modify
[MODDATAIMP-957](https://issues.folio.org/browse/MODDATAIMP-957)
Tested locally

MODDATAIMP-957: register DI_INCOMING_MARC_BIB_RECORD_PARSED

---

descriptors/ModuleDescriptor-template.json

Revert source-storage-records version

[MODSOURCE-732] Revert source-storage-records version

---

NEWS.md
mod-source-record-storage-server/pom.xml
mod-source-record-storage-server/src/main/java/org/folio/dao/QueryExecutorInterceptor.java
mod-source-record-storage-server/src/main/java/org/folio/rest/impl/SourceStorageStreamImpl.java
mod-source-record-storage-server/src/test/java/org/folio/dao/PostgresClientFactoryTest.java
pom.xml

Upgrade source-record-storage to RMB 35.2.0, Vert.x 4.5.4
[MODSOURCE-750](https://folio-org.atlassian.net/browse/MODSOURCE-750)

MODSOURCE-750: Upgrade source-record-storage to RMB 35.2.0, Vert.x 4.5.4

---

mod-source-record-storage-server/src/main/java/org/folio/services/handlers/AuthorityPostProcessingEventHandler.java
mod-source-record-storage-server/src/test/java/org/folio/services/handlers/AuthorityPostProcessingEventHandlerTest.java

Set MARC_AUTHORITY at context during AUTHORITY create at non-match section
Set record at payload context at POST PROCESSING

[MODSOURCE-764] Set MARC_AUTHORITY at context during AUTHORITY create at non-match section

---

mod-source-record-storage-server/pom.xml

Do not delete Kafka topics on postTenant if collection topics is enabled
Updated folio-kafka-wrapper to v3.1.1

Update to folio-kafka-wrapper v3.1.1

---

mod-source-record-storage-server/src/main/java/org/folio/services/util/AdditionalFieldsUtil.java
mod-source-record-storage-server/src/test/java/org/folio/services/AdditionalFieldsUtilTest.java

Removed from condition validation externalHrid to be consistent with [mod-inventory](https://github.com/folio-org/mod-inventory/pull/723)

MODDATAIMP-1052: Error appears when edit via quickMARC MARC Instance shared from Member tenant

---

NEWS.md
mod-source-record-storage-server/src/main/java/org/folio/services/util/AdditionalFieldsUtil.java
mod-source-record-storage-server/src/test/java/org/folio/services/AdditionalFieldsUtilTest.java

[MODINV-1044](https://folio-org.atlassian.net/browse/MODINV-1044) Additional Requirements - Update Data Import logic to normalize OCLC 035 values
update tests
remove spaces periods and "on" prefix

MODINV-1044 Additional Requirements - Update Data Import logic to normalize OCLC 035 values

---

mod-source-record-storage-server/src/main/java/org/folio/services/util/AdditionalFieldsUtil.java

[MODINV-1049](https://folio-org.atlassian.net/browse/MODINV-1049)

MODINV-1049 fix ordering

---

mod-source-record-storage-server/src/main/java/org/folio/services/RecordServiceImpl.java
mod-source-record-storage-server/src/main/java/org/folio/services/exceptions/RecordUpdateException.java
mod-source-record-storage-server/src/test/java/org/folio/services/RecordServiceTest.java

Disallow updating records originated in Linked Data 
Check for linked data id in 999 ff l subfield and throw an error if it is present

MODINV-1002 Disallow update of records originated in Linked Data

---

mod-source-record-storage-server/src/main/java/org/folio/services/domainevent/RecordDomainEventPublisher.java
mod-source-record-storage-server/src/test/java/org/folio/services/domainevent/RecordDomainEventPublisherUnitTest.java

Make RecordDomainEventPublisher provide metadata together with source record ([MODSOURCE-802](https://folio-org.atlassian.net/browse/MODSOURCE-802))
Make RecordDomainEventPublisher publish whole Record

MODSOURCE-802: RecordDomainEventPublisher publishes whole Record

---

mod-source-record-storage-server/src/main/java/org/folio/consumers/AuthorityLinkChunkKafkaHandler.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/actions/MarcBibUpdateModifyEventHandler.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/links/DeleteLinkProcessor.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/links/UpdateLinkProcessor.java
mod-source-record-storage-server/src/main/java/org/folio/util/AuthorityLinksUtils.java
mod-source-record-storage-server/src/test/java/org/folio/services/handlers/links/UpdateLinkProcessorTest.java

Fix links update handling to keep order and repeatable subfields
Adjust logic in UpdateLinkProcessor

MODSOURCE-826 Fix links update handling to keep order and repeatable subfields

---

mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDao.java
mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
mod-source-record-storage-server/src/main/java/org/folio/dao/util/RecordDaoUtil.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/match/AbstractMarcMatchEventHandler.java
mod-source-record-storage-server/src/test/java/org/folio/dao/RecordDaoImplTest.java
mod-source-record-storage-server/src/test/java/org/folio/services/MarcAuthorityMatchEventHandlerTest.java

Allow marc authority submatch, for example:
Add multiple matched record ids to payload if submatch exist, retrieve records during submatch by matched ids
https://folio-org.atlassian.net/browse/MODSOURCE-820

[MODSOURCE-820] Implement marc authority submatch

---

NEWS.md
mod-source-record-storage-server/src/main/java/org/folio/dao/util/RecordDaoUtil.java
mod-source-record-storage-server/src/main/resources/liquibase/tenant/changelog.xml
mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-5.10.0/2024-11-22--16-00-create-indexes-on-marc-indexers-005.xml
mod-source-record-storage-server/src/main/resources/log4j2.properties

[Modsource-816](https://folio-org.atlassian.net/browse/MODSOURCE-816) [RRT] Optimize execution plan for streaming SQL
add indexes

Modsource-816 [RRT] Optimize execution plan for streaming SQL

---

NEWS.md
mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/match/AbstractMarcMatchEventHandler.java

[MODDATAIMP-1133](https://folio-org.atlassian.net/browse/MODDATAIMP-1133) Second update of the same MARC authority / MARC holdings record completes with errors
fix bug in code

MODDATAIMP-1133 Second update of the same MARC authority / MARC holdings record completes with errors

---

mod-source-record-storage-server/src/main/java/org/folio/dao/RecordDaoImpl.java
mod-source-record-storage-server/src/main/java/org/folio/dao/util/TenantUtil.java

Logs with job duration extended.

Logs for marc_indexers job improved.

---

NEWS.md
mod-source-record-storage-client/pom.xml
mod-source-record-storage-server/pom.xml
pom.xml

Release v5.9.7, prepare v5.9.8 development iteration
[MODSOURCE-853](https://folio-org.atlassian.net/browse/MODSOURCE-853)

Prepare v5.9.8 development iteration

---

mod-source-record-storage-server/src/main/java/org/folio/rest/impl/ModTenantAPI.java

Adding additional logging for Tenant API

Adding additional Tenant API logging

---

.github/workflows/postgres.yml
Dockerfile
Jenkinsfile
NEWS.md
mod-source-record-storage-server/pom.xml
pom.xml

Upgrading Java to 21 and rmb.
JIRA: https://folio-org.atlassian.net/browse/MODSOURCE-868

MODSOURCE-868: Migration to Java 21.

---

NEWS.md
mod-source-record-storage-client/pom.xml
mod-source-record-storage-server/pom.xml
pom.xml

Release 5.10.0

---

NEWS.md
mod-source-record-storage-server/src/main/java/org/folio/services/util/parser/lexeme/operand/DateRangeBinaryOperand.java
mod-source-record-storage-server/src/main/resources/liquibase/tenant/changelog.xml
mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-5.10.0/2025-12-03--15-00-create-composite-index-and-update-immutable-to-date-function.xml
mod-source-record-storage-server/src/test/java/org/folio/services/SearchExpressionParserUnitTest.java

The main purpose - increase performance for the /source-storage/stream/marc-record-identifiers POST endpoint.
Function immutable_to_date(text) updated, and now using in the search SQL request, new index was added.
JIRA: https://folio-org.atlassian.net/browse/MODSOURCE-871

Eureka ECS bugfest - 504 Gateway Time-out Error is returned for MARC Search request against Central tenant

---

mod-source-record-storage-server/pom.xml

bump data-import-processing-core version to 4.5.0-SNAPSHOT

MODDICORE-450: bump data-import-processing-core version to 4.5.0-SNAPSHOT

---

NEWS.md
mod-source-record-storage-client/pom.xml
mod-source-record-storage-server/pom.xml
mod-source-record-storage-server/src/main/java/org/folio/services/domainevent/RecordDomainEventPublisher.java
mod-source-record-storage-server/src/test/java/org/folio/services/domainevent/RecordDomainEventPublisherUnitTest.java
pom.xml

Release v5.10.5, prepare v5.10.6 development iteration
[MODSOURCE-893](https://folio-org.atlassian.net/browse/MODSOURCE-893) Fix import of MARC authority record is not tracked as "Original version" in "Version history"

Release v5.10.5, prepare v5.10.6 development iteration

---

mod-source-record-storage-server/src/main/resources/liquibase/tenant/changelog.xml
mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-5.10.0/2025-05-02--11-00-create-index-external-id-covering.xml

[MODSOURCE-900](https://folio-org.atlassian.net/browse/MODSOURCE-900) - Add index to improve Data Export's SQL query performance
Adding index to improve performance of Data Export's SQL query
Adding SQL script, including it to liquibase set.

MODSOURCE-900 - Add index to improve Data Export's SQL query performance

---

NEWS.md
mod-source-record-storage-client/pom.xml
mod-source-record-storage-server/pom.xml
mod-source-record-storage-server/src/main/resources/liquibase/tenant/changelog.xml
mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-5.10.0/2025-05-02--11-00-create-index-external-id-covering.xml
pom.xml

**Release 5.10.6**
[MODSOURCE-904](https://folio-org.atlassian.net/browse/MODSOURCE-904) - Sunflower - add index to improve Data Export's SQL query performance.

Release 5.10.6

---

NEWS.md
mod-source-record-storage-client/pom.xml
mod-source-record-storage-server/pom.xml
mod-source-record-storage-server/src/main/resources/liquibase/tenant/changelog.xml
mod-source-record-storage-server/src/main/resources/liquibase/tenant/scripts/v-5.10.0/2025-05-02--11-00-create-index-external-id-covering.xml
pom.xml

**Release 5.9.15**
[MODSOURCE-900](https://folio-org.atlassian.net/browse/MODSOURCE-900) - Ramsons - add index to improve Data Export's SQL query performance.

Release 5.9.15

---

mod-source-record-storage-client/pom.xml
mod-source-record-storage-server/pom.xml
mod-source-record-storage-server/src/main/java/org/folio/services/handlers/match/AbstractMarcMatchEventHandler.java
pom.xml

Upgrade all dependencies to supported versions for Sunflower.
Bump versions in pom.xml.
Upgrade all dependencies to supported versions for Sunflower.
[MODSOURCE-905](https://folio-org.atlassian.net/browse/MODSOURCE-905)

MODSOURCE-905: Upgrade all dependencies for Sunflower fixing vulns

---

mod-source-record-storage-server/pom.xml

Initialization of SYSTEM_USER_ENABLED via environment variable.
bump version of data-import-utils lib
[MODSOURCE-899](https://folio-org.atlassian.net/browse/MODSOURCE-899)

MODSOURCE-899: SYSTEM_USER_ENABLED env var implementation via standard mechanism, not via JAVA_OPTS
